CREATE VIEW solartis_quotes.taxes AS (
    SELECT 
        JSONExtractString(json, 'SubmissionNumber') AS SubmissionNumber,
        JSONExtractString(json, 'QuoteNumber') AS QuoteNumber,
        JSONExtractString(json, 'PolicyNumber') AS PolicyNumber,
        JSONExtractString(json, 'PolicySubNumber') AS PolicySubNumber,
        JSONExtractString(json, 'EndorsementNumber') AS EndorsementNumber,
        NULL AS AutoLiabilityTaxTaxable,
        NULL AS AutoPhysicalDamageTaxTaxable,
        NULL AS MotorTruckCargoTaxTaxable,
        NULL AS TruckersGeneralLiabilityTaxTaxable,
        NULL AS NonTruckingLiabilityTaxTaxable,
        NULL AS AutoliabilityTaxCode,
        NULL AS AutoLiabilityTaxType,
        NULL AS AutoLiabilityTaxName,
        NULL AS AutoLiabilityTaxDescription,
        NULL AS AutoLiabilityTaxRate,
        NULL AS AutoLiabilityTaxRateType,
        JSONExtractFloat(JSONExtractRaw(location, 'AutoLiability'), 'TotalTaxAmount') AS AutoLiabilityTaxAmount,
        NULL AS AutoLiabilityTaxOrderIndex,
        NULL AS AutoLiabilityTaxAppliedTo,
        NULL AS AutoLiabilityTaxAppliedDate,
        NULL AS AutoPhysicalDamageTaxCode,
        NULL AS AutoPhysicalDamageTaxType,
        NULL AS AutoPhysicalDamageTaxName,
        NULL AS AutoPhysicalDamageTaxDescription,
        NULL AS AutoPhysicalDamageTaxRate,
        NULL AS AutoPhysicalDamageTaxRateType,
        JSONExtractFloat(JSONExtractRaw(location, 'AutoPhysicalDamage'), 'TotalTaxAmount') AS AutoPhysicalDamageTaxAmount,
        NULL AS AutoPhysicalDamageTaxOrderIndex,
        NULL AS AutoPhysicalDamageTaxAppliedTo,
        NULL AS AutoPhysicalDamageTaxAppliedDate,
        NULL AS MotorTruckCargoTaxCode,
        NULL AS MotorTruckCargoTaxType,
        NULL AS MotorTruckCargoTaxName,
        NULL AS MotorTruckCargoTaxDescription,
        NULL AS MotorTruckCargoTaxRate,
        NULL AS MotorTruckCargoTaxRateType,
        JSONExtractFloat(JSONExtractRaw(location, 'MotorTruckCargo'), 'TotalTaxAmount') AS MotorTruckCargoTaxAmount,
        NULL AS MotorTruckCargoTaxOrderIndex,
        NULL AS MotorTruckCargoTaxAppliedTo,
        NULL AS MotorTruckCargoTaxAppliedDate,
        NULL AS TruckersGeneralLiabilityTaxCode,
        NULL AS TruckersGeneralLiabilityTaxType,
        NULL AS TruckersGeneralLiabilityTaxName,
        NULL AS TruckersGeneralLiabilityTaxDescription,
        NULL AS TruckersGeneralLiabilityTaxRate,
        NULL AS TruckersGeneralLiabilityTaxRateType,
        JSONExtractFloat(JSONExtractRaw(location, 'TruckersGeneralLiability'), 'TotalTaxAmount') AS TruckersGeneralLiabilityTaxAmount,
        NULL AS TruckersGeneralLiabilityTaxOrderIndex,
        NULL AS TruckersGeneralLiabilityTaxAppliedTo,
        NULL AS TruckersGeneralLiabilityTaxAppliedDate,
        NULL AS NonTruckingLiabilityTaxCode,
        NULL AS NonTruckingLiabilityTaxType,
        NULL AS NonTruckingLiabilityTaxName,
        NULL AS NonTruckingLiabilityTaxDescription,
        NULL AS NonTruckingLiabilityTaxRate,
        NULL AS NonTruckingLiabilityTaxRateType,
        JSONExtractFloat(JSONExtractRaw(location, 'NonTruckingLiability'), 'TotalTaxAmount') AS NonTruckingLiabilityTaxAmount,
        NULL AS NonTruckingLiabilityTaxOrderIndex,
        NULL AS NonTruckingLiabilityTaxAppliedTo,
        NULL AS NonTruckingLiabilityTaxAppliedDate,
        NULL AS AutoLiabilityMinimumTaxAmount,
        NULL AS AutoPhysicalDamageMinimumTaxAmount,
        NULL AS MotorTruckCargoMinimumTaxAmount,
        NULL AS TruckersGeneralLiabilityMinimumTaxAmount,
        NULL AS NonTruckingLiabilityMinimumTaxAmount,
        NULL AS AutoLiabilityIsFullyEarned,
        NULL AS AutoPhysicalDamageIsFullyEarned,
        NULL AS MotorTruckCargoIsFullyEarned,
        NULL AS TruckersGeneralLiabilityIsFullyEarned,
        NULL AS NonTruckingLiabilityIsFullyEarned
    FROM raw_submissions
    ARRAY JOIN JSONExtractArrayRaw(JSONExtractRaw(json, 'Account'), 'Insured') AS insured
    ARRAY JOIN JSONExtractArrayRaw(JSONExtractRaw(insured, 'CommercialAutomobile'), 'Location') AS location
);