CREATE VIEW if not exists solartis_wip_submissions.locations AS (
    SELECT 
        JSONExtractString(json, 'SubmissionNumber') AS SubmissionNumber,
        JSONExtractString(json, 'QuoteNumber') AS QuoteNumber,
        JSONExtractString(json, 'PolicyNumber') AS PolicyNumber,
        JSONExtractString(json, 'PolicySubNumber') AS PolicySubNumber,
        JSONExtractString(json, 'EndorsementNumber') AS EndorsementNumber,
        JSONExtractString(location, 'LocationNumber') AS LocationNumber,
        JSONExtractString(location, 'PrimaryLocation') AS PrimaryLocation,
        JSONExtractString(location, 'SameAsMailingAddress') AS SameAsMailingAddress,
        JSONExtractString(location, 'LocationFullAddress') AS LocationFullAddress,
        JSONExtractString(location, 'StreetNumberAddress1') AS StreetNumberAddress1,
        JSONExtractString(location, 'StreetNameAddress2') AS StreetNameAddress2,
        JSONExtractString(location, 'City') AS City,
        JSONExtractString(location, 'County') AS County,
        JSONExtractString(location, 'StateRegionCode') AS StateRegionCode,
        JSONExtractString(location, 'StateRegion') AS StateRegion,
        JSONExtractString(location, 'CountryCode') AS CountryCode,
        JSONExtractString(location, 'Country') AS Country,
        JSONExtractString(location, 'Zipcode1') AS Zipcode1,
        JSONExtractString(location, 'Zipcode2') AS Zipcode2,
        JSONExtractString(location, 'LocationPremium') AS LocationPremium,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PremiumPerVehicle') AS AutoLiabilityPremiumPerVehicle,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'BrokerOrServiceFee') AS AutoLiabilityBrokerOrServiceFee,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'IsUMBICoverageSelected') AS AutoLiabilityIsUMBICoverageSelected,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'IsPIPCoverageSelected') AS AutoLiabilityIsPIPCoverageSelected,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'NumberOfPowerUnits') AS AutoLiabilityNumberOfPowerUnits,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'OOSFactor') AS AutoLiabilityOOSFactor,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'FleetSizeFactor') AS AutoLiabilityFleetSizeFactor,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'OOSUIM') AS AutoLiabilityOOSUIM,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'NumberOfLosses') AS AutoLiabilityNumberOfLosses,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'OOSViolationsFactor') AS AutoLiabilityOOSViolationsFactor,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'TotalAdditionalCoveragePremium') AS AutoLiabilityTotalAdditionalCoveragePremium,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'FMCSAOOSViolations') AS AutoLiabilityFMCSAOOSViolations,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'FMCSABasicViolations') AS AutoLiabilityFMCSABasicViolations,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'USDOTFactor') AS AutoLiabilityUSDOTFactor,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'ALLimit') AS ALLimit,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Premium') AS AutoLiabilityPremium,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'FederalFilings') AS AutoLiabilityFederalFilings,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'StateFilings') AS AutoLiabilityStateFilings,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PrimaryandNonContributory') AS AutoLiabilityPrimaryandNonContributory,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'WaiverofSubrogation') AS AutoLiabilityWaiverofSubrogation,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'TotalTaxAmount') AS AutoLiabilityTotalTaxAmount,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'TotalFeeAmount') AS AutoLiabilityTotalFeeAmount,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'Premium') AS AutoLiabilityBIPDCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'Premium') AS AutoLiabilityUMUIMCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'TotalPremium') AS AutoLiabilityUMUIMCoverageTotalPremium,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'YearsInBusinessFactor') AS AutoPhysicalDamageYearsInBusinessFactor,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'BrokerOrServiceFee') AS AutoPhysicalDamageBrokerOrServiceFee,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'IsTICCoverageSelected') AS AutoPhysicalDamageIsTICCoverageSelected,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'IsTSLCoverageSelected') AS AutoPhysicalDamageIsTSLCoverageSelected,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'FMCSAViolations') AS AutoPhysicalDamageFMCSAViolations,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'NumberOfPowerUnits') AS AutoPhysicalDamageNumberOfPowerUnits,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'OOSFactor') AS AutoPhysicalDamageOOSFactor,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'RadiusFactor') AS AutoPhysicalDamageRadiusFactor,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'FleetSizeFactor') AS AutoPhysicalDamageFleetSizeFactor,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'LossRatioFactor') AS AutoPhysicalDamageLossRatioFactor,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Premium') AS AutoPhysicalDamagePremium,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'PremiumPerVehicle') AS AutoPhysicalDamagePremiumPerVehicle,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TotalTIV') AS AutoPhysicalDamageTotalTIV,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TotalTaxAmount') AS AutoPhysicalDamageTotalTaxAmount,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TotalFeeAmount') AS AutoPhysicalDamageTotalFeeAmount,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'TotalPremium') AS AutoPhysicalDamageCoverageTotalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'RadiusFactor1') AS AutoPhysicalDamageCoverageRadiusFactor1,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'RadiusFactor2') AS AutoPhysicalDamageCoverageRadiusFactor2,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'RadiusFactor3') AS AutoPhysicalDamageCoverageRadiusFactor3,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'RadiusFactor4') AS AutoPhysicalDamageCoverageRadiusFactor4,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'DriverAgeFactor') AS AutoPhysicalDamageCoverageDriverAgeFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'DriverViolationFactor') AS AutoPhysicalDamageCoverageDriverViolationFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'DriverCrashesFactor') AS AutoPhysicalDamageCoverageDriverCrashesFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'DriverExperienceFactor') AS AutoPhysicalDamageCoverageDriverExperienceFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'TotalVehicleValue') AS AutoPhysicalDamageCoverageTotalVehicleValue,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'VehicleValueCount') AS AutoPhysicalDamageCoverageVehicleValueCount,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'DriverAgeCount') AS AutoPhysicalDamageCoverageDriverAgeCount,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'TotalDriverAgeValue') AS AutoPhysicalDamageCoverageTotalDriverAgeValue,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'TotalDriverExperienceValue') AS AutoPhysicalDamageCoverageTotalDriverExperienceValue,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'DriverExperienceCount') AS AutoPhysicalDamageCoverageDriverExperienceCount,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'DriverViolationCount') AS AutoPhysicalDamageCoverageDriverViolationCount,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'TotalDriverViolationValue') AS AutoPhysicalDamageCoverageTotalDriverViolationValue,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'DriverCrashesCount') AS AutoPhysicalDamageCoverageDriverCrashesCount,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'TotalDriverCrashesValue') AS AutoPhysicalDamageCoverageTotalDriverCrashesValue,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'WeightedRateCount') AS AutoPhysicalDamageCoverageWeightedRateCount,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'HiredNonOwnedAutoCoverage'), 'Premium') AS HiredNonOwnedAutoCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'HiredNonOwnedAutoCoverage'), 'TotalPremium') AS HiredNonOwnedAutoCoverageTotalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'AggregateLossThreshold') AS AutoLiabilityAggregateLossThreshold,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'FrequencyOfLossThreshold') AS AutoLiabilityFrequencyOfLossThreshold,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'LossRatioThreshold') AS AutoLiabilityLossRatioThreshold,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'TotalNumberOfClaims') AS AutoLiabilityTotalNumberOfClaims,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'TotalClaimsPaid') AS AutoPhysicalDamageTotalClaimsPaid,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'TotalNumberOfClaims') AS AutoPhysicalDamageTotalNumberOfClaims,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'FactorYear1') AS AutoPhysicalDamageFactorYear1,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'FactorYear2') AS AutoPhysicalDamageFactorYear2,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'FactorYear3') AS AutoPhysicalDamageFactorYear3,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'Year1ClaimsPaid') AS AutoPhysicalDamageYear1ClaimsPaid,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'Year2ClaimsPaid') AS AutoPhysicalDamageYear2ClaimsPaid,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'Year3ClaimsPaid') AS AutoPhysicalDamageYear3ClaimsPaid,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'RatioYear2') AS AutoPhysicalDamageRatioYear2,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'RatioYear3') AS AutoPhysicalDamageRatioYear3,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'LossRatioThreshold') AS AutoPhysicalDamageLossRatioThreshold,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'LossCountYear1') AS AutoLiabilityLossCountYear1,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'LossCountYear2') AS AutoLiabilityLossCountYear2,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'LossCountYear3') AS AutoLiabilityLossCountYear3,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'Year1ClaimsPaid') AS AutoLiabilityYear1ClaimsPaid,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'Year2ClaimsPaid') AS AutoLiabilityYear2ClaimsPaid,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'Year3ClaimsPaid') AS AutoLiabilityYear3ClaimsPaid,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'LossCountYear1') AS AutoPhysicalDamageLossCountYear1,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'LossCountYear2') AS AutoPhysicalDamageLossCountYear2,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'LossCountYear3') AS AutoPhysicalDamageLossCountYear3,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'Premium') AS MedicalPaymentsCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PersonalInjuryProtectionCoverage'), 'Premium') AS PersonalInjuryProtectionCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PersonalInjuryProtectionCoverage'), 'TotalPIPCoveragePremium') AS PersonalInjuryProtectionCoverageTotalPIPCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'TowingStorageAndLaborCoverage'), 'TSLPremium') AS TowingStorageAndLaborCoverageTSLPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'TrailerInterchangeCoverage'), 'Premium') AS TrailerInterchangeCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'TrailerInterchangeCoverage'), 'TotalPremium') AS TrailerInterchangeCoverageTotalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'Premium') AS UnderinsuredBodilyInjuryCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'TotalPremium') AS UnderinsuredBodilyInjuryCoverageTotalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'Premium') AS UninsuredBodilyInjuryCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'Premium') AS UninsuredPropertyDamageCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'ILFFactor') AS AutoLiabilityBIPDCoverageILFFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'RadiusToUse') AS AutoLiabilityBIPDCoverageRadiusToUse,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'DriverExperienceFactor') AS AutoLiabilityBIPDCoverageDriverExperienceFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'DriverClassFactor') AS AutoLiabilityBIPDCoverageDriverClassFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'LossHistoryFactor') AS AutoLiabilityBIPDCoverageLossHistoryFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'YearsInBusinessFactor') AS AutoLiabilityBIPDCoverageYearsInBusinessFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'UMBIILF') AS UninsuredBodilyInjuryCoverageUMBIILF,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'DriverExperienceFactor') AS AutoLiabilityUninsuredBodilyInjuryCoverageDriverExperienceFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'LossHistoryFactor') AS UninsuredBodilyInjuryCoverageLossHistoryFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'YearsInBusinessFactor') AS UninsuredBodilyInjuryCoverageYearsInBusinessFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'FleetSizeFactor') AS UninsuredBodilyInjuryCoverageFleetSizeFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'UMPDILF') AS UninsuredPropertyDamageCoverageUMPDILF,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'RadiusFactorToUse') AS UninsuredPropertyDamageCoverageRadiusFactorToUse,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'DriverExperienceFactor') AS AutoLiabilityUninsuredPropertyDamageCoverageDriverExperienceFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'LossHistoryFactor') AS UninsuredPropertyDamageCoverageLossHistoryFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'YearsInBusinessFactor') AS UninsuredPropertyDamageCoverageYearsInBusinessFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'UMBIILF') AS UnderinsuredBodilyInjuryCoverageUMBIILF,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'RadiusFactorToUse') AS UnderinsuredBodilyInjuryCoverageRadiusFactorToUse,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'DriverExperienceFactor') AS AutoLiabilityUnderinsuredBodilyInjuryCoverageDriverExperienceFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'LossHistoryFactor') AS UnderinsuredBodilyInjuryCoverageLossHistoryFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'YearsInBusinessFactor') AS UnderinsuredBodilyInjuryCoverageYearsInBusinessFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'RadiusFactorToUse') AS MedicalPaymentsCoverageRadiusFactorToUse,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'MedPayILF') AS MedPayILF,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'DriverExperienceFactor') AS AutoLiabilityMedicalPaymentsCoverageDriverExperienceFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'DriverClassFactor') AS MedicalPaymentsCoverageDriverClassFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'LossHistoryFactor') AS MedicalPaymentsCoverageLossHistoryFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'YearsInBusinessFactor') AS MedicalPaymentsCoverageYearsInBusinessFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'RadiusToUse') AS AutoLiabilityUMUIMCoverageRadiusToUse,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'HiredNonOnwedAutoCoverage'), 'TotalHNOACoverage') AS TotalHNOACoverage,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'MPYearsofBusinessFactor') AS AutoPhysicalDamageCoverageMPYearsofBusinessFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'MPLossRatioFactor') AS AutoPhysicalDamageCoverageMPLossRatioFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'EquipmentRate') AS AutoPhysicalDamageCoverageEquipmentRate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'MPLossRatio') AS AutoPhysicalDamageCoverageMPLossRatio,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'CompanyYearsInBusinessRange') AS CompanyYearsInBusinessRange,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'Density') AS Density,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'AverageRate') AS AverageRate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'WeightedRate') AS WeightedRate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'WeightPercent') AS WeightPercent,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'OOSCode') AS OOSCode,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'Radius3') AS AutoPhysicalDamageCoverageRadius3,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'Radius4') AS AutoPhysicalDamageCoverageRadius4,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'Radius1') AS AutoPhysicalDamageCoverageRadius1,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'Radius2') AS AutoPhysicalDamageCoverageRadius2,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'DensityRange') AS AutoPhysicalDamageCoverageDensityRange,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'TotalPremium') AS TotalALPremium,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TotalAPDPremium') AS TotalAPDPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'TotalPremium') AS AutoLiabilityBIPDCoverageTotalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'Premium') AS TotalUMBICoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'TotalPremium') AS UninsuredBodilyInjuryCoverageTotalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'UMBICoverageLimit') AS UMBICoverageLimit,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'TotalUMPDCoveragePremium') AS TotalUMPDCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'TotalPremium') AS UninsuredPropertyDamageCoverageTotalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'UMPDCoverageLimit') AS UMPDCoverageLimit,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'TotalUIMBICoveragePremium') AS TotalUIMBICoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'UIMBICoverageLimit') AS UIMBICoverageLimit,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'TotalMedPayCoveragePremium') AS TotalMedPayCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'TotalPremium') AS MedicalPaymentsCoverageTotalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'MedPayCoverageLimit') AS MedPayCoverageLimit,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PersonalInjuryProtectionCoverage'), 'TotalPremium') AS PersonalInjuryProtectionCoverageTotalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PersonalInjuryProtectionCoverage'), 'PIPCoverageLimit') AS PIPCoverageLimit,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'UMUIMCoverageLimit') AS UMUIMCoverageLimit,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredPropertyDamageCoverage'), 'TotalUIMPDCoveragePremium') AS TotalUIMPDCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'TowingStorageAndLaborCoverage'), 'TowingStorageAndLaborCoveragePremium') AS TowingStorageAndLaborCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'TowingStorageAndLaborCoverage'), 'TotalPremium') AS TowingStorageAndLaborCoverageTotalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'TotalModifiedPremium') AS TotalModifiedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'ModifiedPremium') AS ModifiedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'MinimumPremium750pervehicle') AS MinimumPremium750pervehicle,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'MinimumPremiumYearsinBusiness') AS MinimumPremiumYearsinBusiness,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'MinimumPremium60LossRatio') AS MinimumPremium60LossRatio,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'TotalFinalPremium') AS TotalFinalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'AutoPhysicalDamageCoveragePremium') AS AutoPhysicalDamageCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'MinimumPremiumPerVehicleRate') AS MinimumPremiumPerVehicleRate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'VehicleTotalLimit') AS VehicleTotalLimit,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'TotalManualPremium') AS TotalManualPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'FrequencyOfLossThresholdThreeYear') AS AutoLiabilityFrequencyOfLossThresholdThreeYear,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'TotalLossValue') AS AutoLiabilityTotalLossValue,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'LossesConfirmed') AS AutoLiabilityLossesConfirmed,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'LossInformationPending') AS AutoLiabilityLossInformationPending,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'AutoPhysicalDamageRatioYear1') AS AutoPhysicalDamageRatioYear1,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'AutoPhysicalDamageTotalLossValue') AS AutoPhysicalDamageTotalLossValue,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'AutoPhysicalDamageLossesConfirmed') AS AutoPhysicalDamageLossesConfirmed,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'AutoPhysicalDamageLossInformationPending') AS AutoPhysicalDamageLossInformationPending,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'VehicleClassCount') AS AutoLiabilityBIPDCoverageVehicleClassCount,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'TotalVehicleClass') AS AutoLiabilityBIPDCoverageTotalVehicleClass,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'BIPDVehicleClassCount') AS AutoLiabilityBIPDCoverageBIPDVehicleClassCount,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'BIPDTotalVehicleClass') AS AutoLiabilityBIPDCoverageBIPDTotalVehicleClass,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'BIPDDriverAgeFactor') AS AutoLiabilityBIPDCoverageBIPDDriverAgeFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'BIPDDriverExperienceFactor') AS AutoLiabilityBIPDCoverageBIPDDriverExperienceFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'TICPowerUnits') AS TrailerInterchangeCoverageTICPowerUnits,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'TICTrailers') AS TrailerInterchangeCoverageTICTrailers,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'CountForRating') AS TrailerInterchangeCoverageCountForRating,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'TrailerInterchangeRate') AS TrailerInterchangeCoverageTrailerInterchangeRate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'InterchangeRatePerPowerUnit') AS TrailerInterchangeCoverageInterchangeRatePerPowerUnit,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'UnmodifiedPremium') AS TrailerInterchangeCoverageUnmodifiedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'TICModifiedPremium') AS TrailerInterchangeCoverageTICModifiedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'TICMinimumPremium') AS TrailerInterchangeCoverageTICMinimumPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'AutoPhysicalDamageCoverageAvgRatetoUse') AS AutoPhysicalDamageCoverageAvgRatetoUse,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'AutoPhysicalDamageUIIAExposureFactor') AS AutoPhysicalDamageUIIAExposureFactor,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'),'AutoLiabilityIsUMPDCoverageSelected') AS AutoLiabilityIsUMPDCoverageSelected,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'),'AutoLiabilityIsUIMBICoverageSelected') AS AutoLiabilityIsUIMBICoverageSelected,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'),'AutoLiabilityIsMedPayCoverageSelected') AS AutoLiabilityIsMedPayCoverageSelected,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'),'AutoLiabilityIsALUMUIMCoverageSelected') AS AutoLiabilityIsALUMUIMCoverageSelected,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'),'AutoLiabilityIsUIMPDCoverageSelected') AS AutoLiabilityIsUIMPDCoverageSelected,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'),'AutoLiabilityIsHNOACoverageSelected') AS AutoLiabilityIsHNOACoverageSelected,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'BIPDDriverAgePointFactor') AS AutoLiabilityBIPDCoverageBIPDDriverAgePointFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'DriverAgePointsFactor') AS AutoLiabilityBIPDCoverageDriverAgePointsFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'RadiusFactorToUse') AS UninsuredBodilyInjuryCoverageRadiusFactorToUse,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeLimit') AS AutoPhysicalDamageTrailerInterchangeLimit,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'YearsInBusinessFactor') AS AutoLiabilityUMUIMCoverageYearsInBusinessFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'UMUIMDriverExperienceFactor') AS AutoLiabilityUMUIMCoverageUMUIMDriverExperienceFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'DriverViolationFactor') AS AutoLiabilityBIPDCoverageDriverViolationFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'DriverAccidentsFactor') AS AutoLiabilityBIPDCoverageDriverAccidentsFactor,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TowingStorageAndLaborLimit') AS AutoPhysicalDamageTowingStorageAndLaborLimit,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'APDLimit') AS APDLimit,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'DriverAgePointsFactor') AS MedicalPaymentsCoverageDriverAgePointsFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'LossRate') AS AutoLiabilityBIPDCoverageLossRate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'FleetSizeFactor') AS AutoLiabilityBIPDCoverageFleetSizeFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'FleetSizeFactor') AS UninsuredPropertyDamageCoverageFleetSizeFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'FleetSizeFactor') AS UnderinsuredBodilyInjuryCoverageFleetSizeFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'FleetSizeFactor') AS MedicalPaymentsCoverageFleetSizeFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PersonalInjuryProtectionCoverage'), 'FleetSizeFactor') AS PersonalInjuryProtectionCoverageFleetSizeFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'LossHistoryFactor') AS AutoLiabilityUMUIMCoverageLossHistoryFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'UMUIMILF') AS AutoLiabilityUMUIMCoverageUMUIMILF,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'SublineName') AS AutoLiabilityLossesSublineName,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'SublineName') AS AutoPhysicalDamageLossesSublineName,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'MinimumPremiumApplies') AS TrailerInterchangeCoverageMinimumPremiumApplies,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'CalculatedPremium') AS AutoLiabilityCalculatedPremium,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'IsPremiumOverridden') AS AutoLiabilityIsPremiumOverridden,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Deductible') AS AutoPhysicalDamageDeductible,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'CalculatedPremium') AS AutoPhysicalDamageCalculatedPremium,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'IsPremiumOverridden') AS AutoPhysicalDamageIsPremiumOverridden,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'ProratedPriorPremium') AS AutoLiabilityBIPDCoverageProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'FullTermPremium') AS AutoLiabilityBIPDCoverageFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'Density') AS AutoLiabilityBIPDCoverageDensity,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'ProratedPriorPremium') AS UninsuredBodilyInjuryCoverageProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'FullTermPremium') AS UninsuredBodilyInjuryCoverageFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'ProratedPriorPremium') AS UninsuredPropertyDamageCoverageProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'FullTermPremium') AS UninsuredPropertyDamageCoverageFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'ProratedPriorPremium') AS UnderinsuredBodilyInjuryCoverageProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'FullTermPremium') AS UnderinsuredBodilyInjuryCoverageFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'ProratedPriorPremium') AS MedicalPaymentsCoverageProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'FullTermPremium') AS MedicalPaymentsCoverageFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PersonalInjuryProtectionCoverage'), 'ProratedPriorPremium') AS PersonalInjuryProtectionCoverageProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PersonalInjuryProtectionCoverage'), 'FullTermPremium') AS PersonalInjuryProtectionCoverageFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'ProratedPriorPremium') AS AutoLiabilityUMUIMCoverageProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'FullTermPremium') AS AutoLiabilityUMUIMCoverageFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredPropertyDamageCoverage'), 'ProratedPriorPremium') AS UnderinsuredPropertyDamageCoverageProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredPropertyDamageCoverage'), 'FullTermPremium') AS UnderinsuredPropertyDamageCoverageFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'HiredNonOwnedAutoCoverage'), 'ProratedPriorPremium') AS HiredNonOwnedAutoCoverageProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'HiredNonOwnedAutoCoverage'), 'FullTermPremium') AS HiredNonOwnedAutoCoverageFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'CoverageOnPolicyIndicator') AS TrailerInterchangeCoverageCoverageOnPolicyIndicator,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'ProratedPriorPremium') AS TrailerInterchangeCoverageProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'FullTermPremium') AS TrailerInterchangeCoverageFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TowingStorageAndLaborCoverage'), 'ProratedPriorPremium') AS TowingStorageAndLaborCoverageProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TowingStorageAndLaborCoverage'), 'FullTermPremium') AS TowingStorageAndLaborCoverageFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'ProratedPriorPremium') AS AutoPhysicalDamageCoverageProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'FullTermPremium') AS AutoPhysicalDamageCoverageFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'MaxPremium') AS AutoPhysicalDamageCoverageMaxPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'MinimumPremiumType') AS AutoPhysicalDamageCoverageMinimumPremiumType,
        JSONExtractString(location, 'State') AS LocationState,
        JSONExtractString(location, 'AddressCode') AS LocationAddressCode,
        JSONExtractString(location, 'AddressType') AS LocationAddressType,
        JSONExtractString(location, 'ProratedPriorPremium') AS LocationProratedPriorPremium,
        JSONExtractString(location, 'FullTermPremium') AS LocationFullTermPremium,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'ProratedPriorPremium') AS AutoLiabilityProratedPriorPremium,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'FullTermPremium') AS AutoLiabilityFullTermPremium,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'TriaPremium') AS AutoLiabilityTriaPremium,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'FinancialPerformance') AS AutoLiabilityFinancialPerformance,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'DriverSelectionandTraining') AS AutoLiabilityDriverSelectionandTraining,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'ManagementExperienceRiskManagement') AS AutoLiabilityManagementExperienceRiskManagement,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'DriverRouteScore') AS AutoLiabilityDriverRouteScore,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'DriverBehaviorScore') AS AutoLiabilityDriverBehaviorScore,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'ScheduleRatingMod') AS AutoLiabilityScheduleRatingMod,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'FinancialPerformanceReason') AS AutoLiabilityFinancialPerformanceReason,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'DriverSelectionandTrainingReason') AS AutoLiabilityDriverSelectionandTrainingReason,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'ManagementExperienceRiskManagementReason') AS AutoLiabilityManagementExperienceRiskManagementReason,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'DriverRouteScoreReason') AS AutoLiabilityDriverRouteScoreReason,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'DriverBehaviorScoreReason') AS AutoLiabilityDriverBehaviorScoreReason,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'EarnedFeesAndTax') AS AutoLiabilityEarnedFeesAndTax,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnearnedFeesAndTax') AS AutoLiabilityUnearnedFeesAndTax,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'ProratedPriorPremium') AS AutoPhysicalDamageProratedPriorPremium,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'FullTermPremium') AS AutoPhysicalDamageFullTermPremium,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TriaPremium') AS AutoPhysicalDamageTriaPremium,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'FinancialPerformance') AS AutoPhysicalDamageFinancialPerformance,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'DriverSelectionandTraining') AS AutoPhysicalDamageDriverSelectionandTraining,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'ManagementExperienceRiskManagement') AS AutoPhysicalDamageManagementExperienceRiskManagement,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'DriverRouteScore') AS AutoPhysicalDamageDriverRouteScore,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'DriverBehaviorScore') AS AutoPhysicalDamageDriverBehaviorScore,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'ScheduleRatingMod') AS AutoPhysicalDamageScheduleRatingMod,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'FinancialPerformanceReason') AS AutoPhysicalDamageFinancialPerformanceReason,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'DriverSelectionandTrainingReason') AS AutoPhysicalDamageDriverSelectionandTrainingReason,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'ManagementExperienceRiskManagementReason') AS AutoPhysicalDamageManagementExperienceRiskManagementReason,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'DriverRouteScoreReason') AS AutoPhysicalDamageDriverRouteScoreReason,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'DriverBehaviorScoreReason') AS AutoPhysicalDamageDriverBehaviorScoreReason,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'EarnedFeesAndTax') AS AutoPhysicalDamageEarnedFeesAndTax,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'UnearnedFeesAndTax') AS AutoPhysicalDamageUnearnedFeesAndTax,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'TotalLossRatioThreshold') AS AutoLiabilityTotalLossRatioThreshold,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'LossRatioThresholdAL') AS AutoLiabilityLossRatioThresholdAL,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'TotalNumberOfClaimsLastAndCurrentYear') AS AutoLiabilityTotalNumberOfClaimsLastAndCurrentYear,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'TotalLossRatioThreshold') AS AutoPhysicalDamageTotalLossRatioThreshold,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'WrittenPremium') AS AutoLiabilityBIPDCoverageWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'PriorChargedPremium') AS AutoLiabilityBIPDCoveragePriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'WaivedOffPremium') AS AutoLiabilityBIPDCoverageWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'TotalWaivedOffPremium') AS AutoLiabilityBIPDCoverageTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'CoverageStartDate') AS AutoLiabilityBIPDCoverageCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'ChangeEffectiveDate') AS AutoLiabilityBIPDCoverageChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'CoverageStopDate') AS AutoLiabilityBIPDCoverageCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityBIPDCoverage'), 'ChangeType') AS AutoLiabilityBIPDCoverageChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'WrittenPremium') AS UninsuredBodilyInjuryCoverageWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'PriorChargedPremium') AS UninsuredBodilyInjuryCoveragePriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'WaivedOffPremium') AS UninsuredBodilyInjuryCoverageWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'TotalWaivedOffPremium') AS UninsuredBodilyInjuryCoverageTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'CoverageStartDate') AS UninsuredBodilyInjuryCoverageCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'ChangeEffectiveDate') AS UninsuredBodilyInjuryCoverageChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'CoverageStopDate') AS UninsuredBodilyInjuryCoverageCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredBodilyInjuryCoverage'), 'ChangeType') AS UninsuredBodilyInjuryCoverageChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'WrittenPremium') AS UninsuredPropertyDamageCoverageWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'PriorChargedPremium') AS UninsuredPropertyDamageCoveragePriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'WaivedOffPremium') AS UninsuredPropertyDamageCoverageWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'TotalWaivedOffPremium') AS UninsuredPropertyDamageCoverageTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'CoverageStartDate') AS UninsuredPropertyDamageCoverageCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'ChangeEffectiveDate') AS UninsuredPropertyDamageCoverageChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'CoverageStopDate') AS UninsuredPropertyDamageCoverageCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UninsuredPropertyDamageCoverage'), 'ChangeType') AS UninsuredPropertyDamageCoverageChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'WrittenPremium') AS UnderinsuredBodilyInjuryCoverageWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'PriorChargedPremium') AS UnderinsuredBodilyInjuryCoveragePriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'WaivedOffPremium') AS UnderinsuredBodilyInjuryCoverageWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'TotalWaivedOffPremium') AS UnderinsuredBodilyInjuryCoverageTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'CoverageStartDate') AS UnderinsuredBodilyInjuryCoverageCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'ChangeEffectiveDate') AS UnderinsuredBodilyInjuryCoverageChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'CoverageStopDate') AS UnderinsuredBodilyInjuryCoverageCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredBodilyInjuryCoverage'), 'ChangeType') AS UnderinsuredBodilyInjuryCoverageChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'CoverageStartDate') AS MedicalPaymentsCoverageCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'ChangeEffectiveDate') AS MedicalPaymentsCoverageChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'CoverageStopDate') AS MedicalPaymentsCoverageCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'WrittenPremium') AS MedicalPaymentsCoverageWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'PriorChargedPremium') AS MedicalPaymentsCoveragePriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'ChangeType') AS MedicalPaymentsCoverageChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'WaivedOffPremium') AS MedicalPaymentsCoverageWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MedicalPaymentsCoverage'), 'TotalWaivedOffPremium') AS MedicalPaymentsCoverageTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PersonalInjuryProtectionCoverage'), 'WrittenPremium') AS PersonalInjuryProtectionCoverageWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PersonalInjuryProtectionCoverage'), 'PriorChargedPremium') AS PersonalInjuryProtectionCoveragePriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PersonalInjuryProtectionCoverage'), 'WaivedOffPremium') AS PersonalInjuryProtectionCoverageWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PersonalInjuryProtectionCoverage'), 'TotalWaivedOffPremium') AS PersonalInjuryProtectionCoverageTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PersonalInjuryProtectionCoverage'), 'CoverageStartDate') AS PersonalInjuryProtectionCoverageCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PersonalInjuryProtectionCoverage'), 'ChangeEffectiveDate') AS PersonalInjuryProtectionCoverageChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PersonalInjuryProtectionCoverage'), 'CoverageStopDate') AS PersonalInjuryProtectionCoverageCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PersonalInjuryProtectionCoverage'), 'ChangeType') AS PersonalInjuryProtectionCoverageChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'CoverageStartDate') AS AutoLiabilityUMUIMCoverageCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'ChangeEffectiveDate') AS AutoLiabilityUMUIMCoverageChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'CoverageStopDate') AS AutoLiabilityUMUIMCoverageCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'WrittenPremium') AS AutoLiabilityUMUIMCoverageWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'PriorChargedPremium') AS AutoLiabilityUMUIMCoveragePriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'ChangeType') AS AutoLiabilityUMUIMCoverageChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'WaivedOffPremium') AS AutoLiabilityUMUIMCoverageWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'AutoLiabilityUMUIMCoverage'), 'TotalWaivedOffPremium') AS AutoLiabilityUMUIMCoverageTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredPropertyDamageCoverage'), 'WrittenPremium') AS UnderinsuredPropertyDamageCoverageWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredPropertyDamageCoverage'), 'PriorChargedPremium') AS UnderinsuredPropertyDamageCoveragePriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredPropertyDamageCoverage'), 'WaivedOffPremium') AS UnderinsuredPropertyDamageCoverageWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredPropertyDamageCoverage'), 'TotalWaivedOffPremium') AS UnderinsuredPropertyDamageCoverageTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredPropertyDamageCoverage'), 'CoverageStartDate') AS UnderinsuredPropertyDamageCoverageCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredPropertyDamageCoverage'), 'ChangeEffectiveDate') AS UnderinsuredPropertyDamageCoverageChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredPropertyDamageCoverage'), 'CoverageStopDate') AS UnderinsuredPropertyDamageCoverageCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'UnderinsuredPropertyDamageCoverage'), 'ChangeType') AS UnderinsuredPropertyDamageCoverageChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'HiredNonOwnedAutoCoverage'), 'WrittenPremium') AS HiredNonOwnedAutoCoverageWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'HiredNonOwnedAutoCoverage'), 'PriorChargedPremium') AS HiredNonOwnedAutoCoveragePriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'HiredNonOwnedAutoCoverage'), 'WaivedOffPremium') AS HiredNonOwnedAutoCoverageWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'HiredNonOwnedAutoCoverage'), 'TotalWaivedOffPremium') AS HiredNonOwnedAutoCoverageTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'HiredNonOwnedAutoCoverage'), 'CoverageStartDate') AS HiredNonOwnedAutoCoverageCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'HiredNonOwnedAutoCoverage'), 'ChangeEffectiveDate') AS HiredNonOwnedAutoCoverageChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'HiredNonOwnedAutoCoverage'), 'CoverageStopDate') AS HiredNonOwnedAutoCoverageCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'HiredNonOwnedAutoCoverage'), 'ChangeType') AS HiredNonOwnedAutoCoverageChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TowingStorageAndLaborCoverage'), 'WrittenPremium') AS TowingStorageAndLaborCoverageWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TowingStorageAndLaborCoverage'), 'PriorChargedPremium') AS TowingStorageAndLaborCoveragePriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TowingStorageAndLaborCoverage'), 'WaivedOffPremium') AS TowingStorageAndLaborCoverageWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TowingStorageAndLaborCoverage'), 'TotalWaivedOffPremium') AS TowingStorageAndLaborCoverageTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TowingStorageAndLaborCoverage'), 'CoverageStartDate') AS TowingStorageAndLaborCoverageCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TowingStorageAndLaborCoverage'), 'ChangeEffectiveDate') AS TowingStorageAndLaborCoverageChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TowingStorageAndLaborCoverage'), 'CoverageStopDate') AS TowingStorageAndLaborCoverageCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TowingStorageAndLaborCoverage'), 'ChangeType') AS TowingStorageAndLaborCoverageChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'WrittenPremium') AS AutoPhysicalDamageCoverageWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'PriorChargedPremium') AS AutoPhysicalDamageCoveragePriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'WaivedOffPremium') AS AutoPhysicalDamageCoverageWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'TotalWaivedOffPremium') AS AutoPhysicalDamageCoverageTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'CoverageStartDate') AS AutoPhysicalDamageCoverageCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'ChangeEffectiveDate') AS AutoPhysicalDamageCoverageChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'CoverageStopDate') AS AutoPhysicalDamageCoverageCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'AutoPhysicalDamageCoverage'), 'ChangeType') AS AutoPhysicalDamageCoverageChangeType,
        JSONExtractString(location, 'CoverageStartDate') AS LocationCoverageStartDate,
        JSONExtractString(location, 'ChangeEffectiveDate') AS LocationChangeEffectiveDate,
        JSONExtractString(location, 'CoverageStopDate') AS LocationCoverageStopDate,
        JSONExtractString(location, 'WrittenPremium') AS LocationWrittenPremium,
        JSONExtractString(location, 'PriorChargedPremium') AS LocationPriorChargedPremium,
        JSONExtractString(location, 'ChangeType') AS LocationChangeType,
        JSONExtractString(location, 'WaivedOffPremium') AS LocationWaivedOffPremium,
        JSONExtractString(location, 'TotalWaivedOffPremium') AS LocationTotalWaivedOffPremium,
        JSONExtractString(location, 'TotalTaxAmount') AS LocationTotalTaxAmount,
        JSONExtractString(location, 'TotalFeeAmount') AS LocationTotalFeeAmount,
        JSONExtractString(location, 'TotalSurchargeAmount') AS LocationTotalSurchargeAmount,
        JSONExtractString(location, 'TotalPremium') AS LocationTotalPremium,
        JSONExtractString(location, 'BrokerOrServiceFee') AS LocationBrokerOrServiceFee,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'ELDOnly') AS AutoLiabilityELDOnly,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'DashCamera') AS AutoLiabilityDashCamera,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'TotalSurchargeAmount') AS AutoLiabilityTotalSurchargeAmount,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'CarrierName') AS AutoLiabilityCarrierName,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'LossesCoverageStartDate') AS AutoLiabilityLossesCoverageStartDate,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'ChangeEffectiveDate') AS AutoLiabilityChangeEffectiveDate,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'CoverageStopDate') AS AutoLiabilityCoverageStopDate,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'WrittenPremium') AS AutoLiabilityWrittenPremium,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'PriorChargedPremium') AS AutoLiabilityPriorChargedPremium,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'WaivedOffPremium') AS AutoLiabilityWaivedOffPremium,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'TotalWaivedOffPremium') AS AutoLiabilityTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'IsMinimumTaxApplied') AS AutoLiabilityIsMinimumTaxApplied,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'ALAgencyCommissionOverride') AS AutoLiabilityALAgencyCommissionOverride,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'ALPremiumOverride') AS AutoLiabilityALPremiumOverride,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'ALPolicyFeeOverride') AS AutoLiabilityALPolicyFeeOverride,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'ALUWFeeOverride') AS AutoLiabilityALUWFeeOverride,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'BrokerPayesTax') AS AutoLiabilityBrokerPayesTax,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'MinimumDeductible') AS AutoLiabilityMinimumDeductible,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'ALAgencyCommissionAmount') AS AutoLiabilityALAgencyCommissionAmount,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'RatingPlan') AS AutoLiabilityRatingPlan,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TotalSurchargeAmount') AS AutoPhysicalDamageTotalSurchargeAmount,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'CarrierName') AS AutoPhysicalDamageCarrierName,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'CoverageStartDate') AS AutoPhysicalDamageCoverageStartDate,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'ChangeEffectiveDate') AS AutoPhysicalDamageChangeEffectiveDate,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'CoverageStopDate') AS AutoPhysicalDamageCoverageStopDate,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'WrittenPremium') AS AutoPhysicalDamageWrittenPremium,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'PriorChargedPremium') AS AutoPhysicalDamagePriorChargedPremium,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'WaivedOffPremium') AS AutoPhysicalDamageWaivedOffPremium,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TotalWaivedOffPremium') AS AutoPhysicalDamageTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'IsMinimumTaxApplied') AS AutoPhysicalDamageIsMinimumTaxApplied,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'APDAgencyCommissionOverride') AS AutoPhysicalDamageAPDAgencyCommissionOverride,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'APDPremiumOverride') AS AutoPhysicalDamageAPDPremiumOverride,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'APDPolicyFeeOverride') AS AutoPhysicalDamageAPDPolicyFeeOverride,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'APDUWFeeOverride') AS AutoPhysicalDamageAPDUWFeeOverride,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'BrokerPayesTax') AS AutoPhysicalDamageBrokerPayesTax,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'MinimumDeductible') AS AutoPhysicalDamageMinimumDeductible,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'APDAgencyCommissionAmount') AS AutoPhysicalDamageAPDAgencyCommissionAmount,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'RatingPlan') AS AutoPhysicalDamageRatingPlan,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'ChangeType') AS AutoLiabilityChangeType,
        JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'ChangeType') AS AutoPhysicalDamageChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'WrittenPremium') AS TrailerInterchangeCoverageWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'PriorChargedPremium') AS TrailerInterchangeCoveragePriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'WaivedOffPremium') AS TrailerInterchangeCoverageWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'TotalWaivedOffPremium') AS TrailerInterchangeCoverageTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'CoverageStartDate') AS TrailerInterchangeCoverageCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'ChangeEffectiveDate') AS TrailerInterchangeCoverageChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'CoverageStopDate') AS TrailerInterchangeCoverageCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'ChangeType') AS TrailerInterchangeCoverageChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'CoverageOnPolicyIndicator') AS AutoPhysicalDamageTrailerInterchangeCoverageCoverageOnPolicyIndicator,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'TrailerInterchangeCoverage'), 'ProratedPriorPremium') AS AutoPhysicalDamageTrailerInterchangeCoverageProratedPriorPremium,
        JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'CoverageStartDate') AS AutoLiabilityCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'ChangeEffectiveDate') AS AutoLiabilityLossesChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'CoverageStopDate') AS AutoLiabilityLossesCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'WrittenPremium') AS AutoLiabilityLossesWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'PriorChargedPremium') AS AutoLiabilityLossesPriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'ChangeType') AS AutoLiabilityLossesChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'WaivedOffPremium') AS AutoLiabilityLossesWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoLiability'), 'Losses'), 'TotalWaivedOffPremium') AS AutoLiabilityLossesTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'CoverageStartDate') AS AutoPhysicalDamageLossesCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'ChangeEffectiveDate') AS AutoPhysicalDamageLossesChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'CoverageStopDate') AS AutoPhysicalDamageLossesCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'WrittenPremium') AS AutoPhysicalDamageLossesWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'PriorChargedPremium') AS AutoPhysicalDamageLossesPriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'ChangeType') AS AutoPhysicalDamageLossesChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'WaivedOffPremium') AS AutoPhysicalDamageLossesWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(location, 'AutoPhysicalDamage'), 'Losses'), 'TotalWaivedOffPremium') AS AutoPhysicalDamageLossesTotalWaivedOffPremium
    FROM solartis_wip_submissions.raw_submissions
    ARRAY JOIN JSONExtractArrayRaw(JSONExtractRaw(json, 'Account'), 'Insured') AS insured
    ARRAY JOIN JSONExtractArrayRaw(JSONExtractRaw(insured, 'CommercialAutomobile'), 'Location') AS location
);