CREATE VIEW if not exists solartis_wip_submissions.submissions AS (
        SELECT
        JSONExtractString(json, 'SubmissionNumber') AS SubmissionNumber,
        JSONExtractString(json, 'QuoteNumber') AS QuoteNumber,
        JSONExtractString(json, 'PolicyNumber') AS PolicyNumber,
        JSONExtractString(json, 'PolicySubNumber') AS PolicySubNumber,
        JSONExtractString(json, 'EndorsementNumber') AS EndorsementNumber,
        JSONExtractString(insured, 'DBA') AS DBA,
        JSONExtractString(insured, 'EntityType') AS EntityType,
        JSONExtractString(insured, 'DescriptionOfOperations') AS DescriptionOfOperations,
        JSONExtractString(insured, 'AgentNumber') AS AgentNumber,
        JSONExtractString(insured, 'AgencyNumber') AS AgencyNumber,
        JSONExtractString(insured, 'InsuredName') AS InsuredName,
        JSONExtractString(insured, 'InsuredFullAddress') AS InsuredFullAddress,
        JSONExtractString(insured, 'HasCompanyNotCancelledMoreThanThreeTimes') AS HasCompanyNotCancelledMoreThanThreeTimes,
        JSONExtractString(insured, 'HasNoBankruptcies') AS HasNoBankruptcies,
        JSONExtractString(insured, 'DotNumber') AS DotNumber,
        JSONExtractString(insured, 'TotalPowerUnits') AS TotalPowerUnits,
        JSONExtractString(JSONExtractString(json, 'CommercialAutomobile'), 'EffectiveDate') AS EffectiveDate,
        JSONExtractString(JSONExtractString(json, 'CommercialAutomobile'), 'ExpirationDate') AS ExpirationDate,
        JSONExtractString(JSONExtractString(json, 'CommercialAutomobile'), 'TotalPremium') AS TotalPremium,
        JSONExtractString(json, 'BoundBy') AS BoundBy,
        JSONExtractString(json, 'IssuedBy') AS IssuedBy,
        JSONExtractString(json, 'TransactionType') AS TransactionType,
        JSONExtractString(JSONExtractString(json, 'CommercialAutomobile'), 'TotalDrivers') AS TotalDrivers,
        JSONExtractString(JSONExtractString(json, 'CommercialAutomobile'), 'DriverAgePointsFactor') AS DriverAgePointsFactor,
        JSONExtractString(JSONExtractString(json, 'CommercialAutomobile'), 'DriverAgeBracket') AS DriverAgeBracket,
        JSONExtractString(JSONExtractString(json, 'CommercialAutomobile'), 'ViolationFactortoUse') AS ViolationFactortoUse,
        JSONExtractString(JSONExtractString(json, 'CommercialAutomobile'), 'AccidentsFactor') AS AccidentsFactor,
        JSONExtractString(JSONExtractString(json, 'CommercialAutomobile'), 'TechnologyFactor') AS TechnologyFactor,
        JSONExtractString(contact, 'PhoneNumber') AS PhoneNumber,
        JSONExtractString(contact, 'Fax') AS Fax,
        JSONExtractString(contact, 'EmailAddress') AS EmailAddress,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'OperationType') AS OperationType,
        NULL as Commodity,
        JSONExtractString(address, 'StreetNumberAddress1') AS StreetNumberAddress1,
        JSONExtractString(address, 'StreetNameAddress2') AS StreetNameAddress2,
        JSONExtractString(address, 'City') AS City,
        JSONExtractString(address, 'County') AS County,
        JSONExtractString(address, 'StateRegionCode') AS StateRegionCode,
        JSONExtractString(address, 'StateRegion') AS StateRegion,
        JSONExtractString(address, 'CountryCode') AS CountryCode,
        JSONExtractString(address, 'Country') AS Country,
        JSONExtractString(address, 'ZipCode1') AS Zipcode1,
        JSONExtractString(address, 'ZipCode2') AS Zipcode2,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'OperatingStatus') AS OperatingStatus,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'OperationClassification') AS OperationClassification,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'CarrierOperations') AS CarrierOperations,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'CompanyConduct') AS CompanyConduct,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'YearsInBusinessYrs') AS YearsInBusinessYrs,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'YearsInBusinessMonths') AS YearsInBusinessMonths,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'TotalRadius') AS TotalRadius,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'Radius') AS Radius,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'PercentageOfHauls') AS PercentageOfHauls,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'Radius0To50') AS Radius0To50,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'Radius51To200') AS Radius51To200,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'Radius201To500') AS Radius201To500,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'Radius501Plus') AS Radius501Plus,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'EntityType') AS OperationsEntityType,
        JSONExtractString(json, 'PolicyEffectiveDate') AS PolicyEffectiveDate,
        JSONExtractString(json, 'PolicyExpirationDate') AS PolicyExpirationDate,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'),'TotalAccidents') AS TotalAccidents,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'),'TotalViolations') AS TotalViolations,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MEDPAYTotalDriverAgePointsValue') AS MEDPAYTotalDriverAgePointsValue,
        JSONExtractString(json, 'BoundDate') AS BoundDate,
        JSONExtractString(json, 'IssuedDate') AS IssuedDate,
        JSONExtractString(json, 'EndorsementEffectiveDate') AS EndorsementEffectiveDate,
        JSONExtractString(json, 'CancellationDate') AS CancellationDate,
        JSONExtractString(json, 'CancellationType') AS CancellationType,
        JSONExtractString(json, 'CancellationReason') AS CancellationReason,
        JSONExtractString(json, 'CancellationEffectiveDate') AS CancellationEffectiveDate,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'CancelledByPriorCarrier') AS CancelledByPriorCarrier,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'CancellationFactor') AS CancellationFactor,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'ProrataFactor') AS ProrataFactor,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'ProratedChangeBasePremium') AS ProratedChangeBasePremium,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'ProratedBasePremium') AS ProratedBasePremium,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'ChangeProrateFactor') AS ChangeProrateFactor,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'ProratedPriorBasePremium') AS ProratedPriorBasePremium,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'ProhibitedCargo') AS ProhibitedCargo,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'ExcludedOperations') AS ExcludedOperations,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'ExcludedCommodities') AS ExcludedCommodities,
        JSONExtractString(json, 'SubmissionType') AS SubmissionType,
        JSONExtractString(json, 'QuoteFullNumber') AS QuoteFullNumber,
        JSONExtractString(json, 'QuoteValidUntil') AS QuoteValidUntil,
        JSONExtractString(json, 'QuoteOfferedDate') AS QuoteOfferedDate,
        JSONExtractString(json, 'IsModifiedQuote') AS IsModifiedQuote,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'PrimaryandNonContributory') AS TruckersGeneralLiabilityPrimaryandNonContributory,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'NumberOfPowerUnits') AS TruckersGeneralLiabilityNumberOfPowerUnits,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TotalPremium') AS TruckersGeneralLiabilityTotalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'Premium') AS TruckersGeneralLiabilityPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'CarrierName') AS TruckersGeneralLiabilityCarrierName,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'ChangeType') AS TruckersGeneralLiabilityChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'WaiverofSubrogation') AS TruckersGeneralLiabilityWaiverofSubrogation,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TotalTaxAmount') AS TruckersGeneralLiabilityTotalTaxAmount,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TotalFeeAmount') AS TruckersGeneralLiabilityTotalFeeAmount,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'BrokerOrServiceFee') AS TruckersGeneralLiabilityBrokerOrServiceFee,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'PrimaryandNonContributory') AS NonTruckingLiabilityPrimaryandNonContributory,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NumberOfPowerUnits') AS NonTruckingLiabilityNumberOfPowerUnits,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'TotalPremium') AS NonTruckingLiabilityTotalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'Premium') AS NonTruckingLiabilityPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'CarrierName') AS NonTruckingLiabilityCarrierName,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'ChangeType') AS NonTruckingLiabilityChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'WaiverofSubrogation') AS NonTruckingLiabilityWaiverofSubrogation,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'TotalTaxAmount') AS NonTruckingLiabilityTotalTaxAmount,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'TotalFeeAmount') AS NonTruckingLiabilityTotalFeeAmount,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'BrokerOrServiceFee') AS NonTruckingLiabilityBrokerOrServiceFee,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'CoveredVehicleLimit') AS MotorTruckCargoCoveredVehicleLimit,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'LossLimit') AS MotorTruckCargoLossLimit,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'RefrigerationBreakdownCoverageLimit') AS MotorTruckCargoRefrigerationBreakdownCoverageLimit,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'UnattendedCoveredVehicleLimit') AS MotorTruckCargoUnattendedCoveredVehicleLimit,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'DebrisRemovalCoverageLimit') AS MotorTruckCargoDebrisRemovalCoverageLimit,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeLimit') AS MotorTruckCargoTrailerInterchangeLimit,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'NumberOfPowerUnits') AS MotorTruckCargoNumberOfPowerUnits,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'OOSViolations') AS MotorTruckCargoOOSViolations,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'OOSFactor') AS MotorTruckCargoOOSFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TotalPremium') AS MotorTruckCargoTotalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'PremiumPerVehicle') AS MotorTruckCargoPremiumPerVehicle,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoLimit') AS MotorTruckCargoMotorTruckCargoLimit,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoDeductible') AS MotorTruckCargoMotorTruckCargoDeductible,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Premium') AS MotorTruckCargoPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'ChangeType') AS MotorTruckCargoChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TotalTaxAmount') AS MotorTruckCargoTotalTaxAmount,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TotalFeeAmount') AS MotorTruckCargoTotalFeeAmount,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'BrokerOrServiceFee') AS MotorTruckCargoBrokerOrServiceFee,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Refrigeration') AS MotorTruckCargoRefrigeration,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'Losses'), 'LossesConfirmed') AS TruckersGeneralLiabilityLossesConfirmed,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'Losses'), 'LossInformationPending') AS TruckersGeneralLiabilityLossInformationPending,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Losses'), 'LossCountYear1') AS MotorTruckCargoLossCountYear1,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Losses'), 'LossCountYear2') AS MotorTruckCargoLossCountYear2,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Losses'), 'LossCountYear3') AS MotorTruckCargoLossCountYear3,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Losses'), 'Year1ClaimsPaid') AS MotorTruckCargoYear1ClaimsPaid,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Losses'), 'Year2ClaimsPaid') AS MotorTruckCargoYear2ClaimsPaid,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Losses'), 'Year3ClaimsPaid') AS MotorTruckCargoYear3ClaimsPaid,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'Losses'), 'LossCountYear1') AS TruckersGeneralLiabilityLossCountYear1,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'Losses'), 'LossCountYear2') AS TruckersGeneralLiabilityLossCountYear2,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'Losses'), 'LossCountYear3') AS TruckersGeneralLiabilityLossCountYear3,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'Losses'), 'Year1ClaimsPaid') AS TruckersGeneralLiabilityYear1ClaimsPaid,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'Losses'), 'Year2ClaimsPaid') AS TruckersGeneralLiabilityYear2ClaimsPaid,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'Losses'), 'Year3ClaimsPaid') AS TruckersGeneralLiabilityYear3ClaimsPaid,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'Premium') AS MotorTruckCargoCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'TotalPremium') AS MotorTruckCargoCoverageTotalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'PolicyTermPremium') AS MotorTruckCargoCoveragePolicyTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'PremiumPriorToProrata') AS MotorTruckCargoCoveragePremiumPriorToProrata,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'ProRateFactor') AS MotorTruckCargoCoverageProRateFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'MinimumPremiumApplied') AS MotorTruckCargoCoverageMinimumPremiumApplied,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'CoverageOnPolicyIndicator') AS MotorTruckCargoCoverageCoverageOnPolicyIndicator,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'TotalPremium') AS NonTruckingLiabilityCoverageTotalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'BaseRate') AS NonTruckingLiabilityCoverageBaseRate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'CoverageOnPolicyIndicator') AS NonTruckingLiabilityCoverageCoverageOnPolicyIndicator,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'MinimumPremiumApplied') AS NonTruckingLiabilityCoverageMinimumPremiumApplied,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'Premium') AS TrailerInterchangeCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'TotalPremium') AS TrailerInterchangeCoverageTotalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'TotalPremium') AS TruckersGeneralLiabilityCoverageTotalPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'PolicyTermPremium') AS TruckersGeneralLiabilityCoveragePolicyTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'PremiumPriorToProrata') AS TruckersGeneralLiabilityCoveragePremiumPriorToProrata,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'ProRateFactor') AS TruckersGeneralLiabilityCoverageProRateFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'MinimumPremiumApplied') AS TruckersGeneralLiabilityCoverageMinimumPremiumApplied,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'CoverageOnPolicyIndicator') AS TruckersGeneralLiabilityCoverageCoverageOnPolicyIndicator,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'WrittenPremium') AS NonTruckingLiabilityWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'FullTermPremium') AS NonTruckingLiabilityFullTermPremium,
        JSONExtractString(insured, 'FMCSAViolations') AS FMCSAViolations,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'BIPDTotalDriverAgePointsValue') AS BIPDTotalDriverAgePointsValue,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'),'DriverClassCount') AS CommercialAutomobileDriverClassCount,
        JSONExtractString(json, 'QuoteStatus') AS QuoteStatus,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'Losses'), 'LossesConfirmed') AS NonTruckingLiabilityLossesConfirmed,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'Losses'), 'LossInformationPending') AS NonTruckingLiabilityLossInformationPending,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Losses'), 'LossesConfirmed') AS MotorTruckCargoLossesConfirmed,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Losses'), 'LossInformationPending') AS MotorTruckCargoLossInformationPending,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'DriverAgeCount') AS CommercialAutomobileDriverAgeCount,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalDriverAgeValue') AS CommercialAutomobileTotalDriverAgeValue,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'DriverExperienceCount') AS CommercialAutomobileDriverExperienceCount,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'AvgDriverExperience') AS CommercialAutomobileAvgDriverExperience,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'DriverViolationCount') AS CommercialAutomobileDriverViolationCount,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalDriverViolationValue') AS CommercialAutomobileTotalDriverViolationValue,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'AvgDriverViolation') AS CommercialAutomobileAvgDriverViolation,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'DriverCrashesCount') AS CommercialAutomobileDriverCrashesCount,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalDriverCrashesValue') AS CommercialAutomobileTotalDriverCrashesValue,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'AvgDriverCrashes') AS CommercialAutomobileAvgDriverCrashes,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalDriverClassValue') AS CommercialAutomobileTotalDriverClassValue,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'DriverAgePointsCount') AS CommercialAutomobileDriverAgePointsCount,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalDriverAgePointsValue') AS CommercialAutomobileTotalDriverAgePointsValue,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'BIPDTotalDriverExperienceValue') AS CommercialAutomobileBIPDTotalDriverExperienceValue,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'UMBITotalDriverExperienceValue') AS CommercialAutomobileUMBITotalDriverExperienceValue,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'UMPDTotalDriverExperienceValue') AS CommercialAutomobileUMPDTotalDriverExperienceValue,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'UIMBITotalDriverExperienceValue') AS CommercialAutomobileUIMBITotalDriverExperienceValue,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MEDPAYTotalDriverExperienceValue') AS CommercialAutomobileMEDPAYTotalDriverExperienceValue,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'PIPTotalDriverExperienceValue') AS CommercialAutomobilePIPTotalDriverExperienceValue,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Premium') AS CommercialAutomobilePremium,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'DriverAge') AS CommercialAutomobileDriverAge,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'IsEndorsementRating') AS CommercialAutomobileIsEndorsementRating,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'PolicyEffectiveDate') AS CommercialAutomobilePolicyEffectiveDate,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalClaimsCountYear1') AS CommercialAutomobileTotalClaimsCountYear1,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalClaimsCountYear2') AS CommercialAutomobileTotalClaimsCountYear2,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalClaimsCountYear3') AS CommercialAutomobileTotalClaimsCountYear3,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalClaimsPaidYear1') AS CommercialAutomobileTotalClaimsPaidYear1,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalClaimsPaidYear2') AS CommercialAutomobileTotalClaimsPaidYear2,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalClaimsPaidYear3') AS CommercialAutomobileTotalClaimsPaidYear3,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'BIPDTotalDriverAgeValue') AS CommercialAutomobileBIPDTotalDriverAgeValue,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'BIPDDriverAccidentsFactor') AS CommercialAutomobileBIPDDriverAccidentsFactor,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'BIPDTotalDriverClassValue') AS CommercialAutomobileBIPDTotalDriverClassValue,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MEDPAYTotalDriverClassValue') AS CommercialAutomobileMEDPAYTotalDriverClassValue,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'PIPTotalDriverClassValue') AS CommercialAutomobilePIPTotalDriverClassValue,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'UMUIMTotalDriverExperienceValue') AS CommercialAutomobileUMUIMTotalDriverExperienceValue,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'PrimaryState') AS CommercialAutomobilePrimaryState,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Year1') AS CommercialAutomobileYear1,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Year2') AS CommercialAutomobileYear2,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Year3') AS CommercialAutomobileYear3,
        JSONExtractString(contact, 'FirstName1') AS InsuredContactFirstName1,
        JSONExtractString(contact, 'LastName2') AS InsuredContactLastName2,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'Losses'), 'LossCountYear1') AS NonTruckingLiabilityLossCountYear1,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'Losses'), 'LossCountYear2') AS NonTruckingLiabilityLossCountYear2,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'Losses'), 'LossCountYear3') AS NonTruckingLiabilityLossCountYear3,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'Losses'), 'Year1ClaimsPaid') AS NonTruckingLiabilityYear1ClaimsPaid,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'Losses'), 'Year2ClaimsPaid') AS NonTruckingLiabilityYear2ClaimsPaid,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'Losses'), 'Year3ClaimsPaid') AS NonTruckingLiabilityYear3ClaimsPaid,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'WrittenPremium') AS MotorTruckCargoWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'FullTermPremium') AS MotorTruckCargoFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'ProratedPremium') AS MotorTruckCargoProratedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'ProratedPriorPremium') AS MotorTruckCargoProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'ChangeProrateFactor') AS MotorTruckCargoChangeProrateFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'ChangePremium') AS MotorTruckCargoChangePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'ProratedChangePremium') AS MotorTruckCargoProratedChangePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'WaivedOffPremium') AS MotorTruckCargoWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'TotalWaivedOffPremium') AS MotorTruckCargoTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'MTCRate') AS MotorTruckCargoCoverageMTCRate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'UnmodifiedPremium') AS MotorTruckCargoCoverageUnmodifiedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'VehicleMTCPremium') AS MotorTruckCargoCoverageVehicleMTCPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'ProratedPremium') AS NonTruckingLiabilityProratedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'ProratedPriorPremium') AS NonTruckingLiabilityProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'ChangeProrateFactor') AS NonTruckingLiabilityChangeProrateFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'ChangePremium') AS NonTruckingLiabilityChangePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'ProratedChangePremium') AS NonTruckingLiabilityProratedChangePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'WaivedOffPremium') AS NonTruckingLiabilityWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'TotalWaivedOffPremium') AS NonTruckingLiabilityTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'PolicyTermPremium') AS NonTruckingLiabilityCoveragePolicyTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'BaseRateFactor') AS NonTruckingLiabilityCoverageBaseRateFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'BaseRate') AS TruckersGeneralLiabilityBaseRate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'WrittenPremium') AS TruckersGeneralLiabilityWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'FullTermPremium') AS TruckersGeneralLiabilityFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'ProratedPremium') AS TruckersGeneralLiabilityProratedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'ProratedPriorPremium') AS TruckersGeneralLiabilityProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'ChangeProrateFactor') AS TruckersGeneralLiabilityChangeProrateFactor,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'ChangePremium') AS TruckersGeneralLiabilityChangePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'ProratedChangePremium') AS TruckersGeneralLiabilityProratedChangePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'WaivedOffPremium') AS TruckersGeneralLiabilityWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'TotalWaivedOffPremium') AS TruckersGeneralLiabilityTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'Premium') AS TruckersGeneralLiabilityCoveragePremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'ChangeType') AS MotorTruckCargoCoverageChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'ChangeType') AS NonTruckingLiabilityCoverageChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'ChangeType') AS TruckersGeneralLiabilityCoverageChangeType,
        JSONExtractString(json, 'ParentPolicyNumber') AS ParentPolicyNumber,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalBasePremium') AS TotalBasePremium,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MunicipalityCode') AS MunicipalityCode,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'CountOfCriticalViolationCode') AS CountOfCriticalViolationCode,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'CountOfSaferScoreThreshold') AS CountOfSaferScoreThreshold,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'RadiusRange') AS RadiusRange,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'TICPowerUnits') AS TrailerInterchangeCoverageTICPowerUnits,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'TICTrailers') AS TrailerInterchangeCoverageTICTrailers,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'CountForRating') AS TrailerInterchangeCoverageCountForRating,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'TrailerInterchangeRate') AS TrailerInterchangeCoverageTrailerInterchangeRate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'InterchangeRatePerPowerUnit') AS TrailerInterchangeCoverageInterchangeRatePerPowerUnit,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'UnmodifiedPremium') AS TrailerInterchangeCoverageUnmodifiedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'TICModifiedPremium') AS TrailerInterchangeCoverageTICModifiedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'TICMinimumPremium') AS TrailerInterchangeCoverageTICMinimumPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'UIIAExposureFactor') AS MotorTruckCargoUIIAExposureFactor,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'UIIAExposure') AS MotorTruckCargoUIIAExposure,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'Losses'), 'SublineName') AS NonTruckingLiabilityLossesSublineName,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Losses'), 'SublineName') AS MotorTruckCargoLossesSublineName,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'Losses'), 'SublineName') AS TruckersGeneralLiabilityLossesSublineName,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalAgencyCommissionAmount') AS TotalAgencyCommissionAmount,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'BrokerPayesTax') AS CommercialAutomobileTruckersGeneralLiabilityBrokerPayesTax,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'MinimumDeductible') AS TruckersGeneralLiabilityMinimumDeductible,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'AgencyCommissionAmount') AS TGLAgencyCommissionAmount,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'BrokerPayesTax') AS NonTruckingLiabilityBrokerPayesTax,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'MinimumDeductible') AS NonTruckingLiabilityMinimumDeductible,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'AgencyCommissionAmount') AS NTLAgencyCommissionAmount,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'BrokerPayesTax') AS MotorTruckCargoBrokerPayesTax,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MinimumDeductible') AS MotorTruckCargoMinimumDeductible,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'AgencyCommissionAmount') AS MTCAgencyCommissionAmount,
        NULL AS Classification,
        JSONExtractString(json, 'CreatedAt') AS CreatedAt,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'PFCStatus') AS PFCStatus,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'PFCAgencyCode') AS PremiumFinancePFCAgencyCode,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'NewVentureDownPayment') AS PremiumFinanceNewVentureDownPayment,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'OldVentureDownPayment') AS PremiumFinanceOldVentureDownPayment,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'AgencyCommission'), 'AgencyType') AS AgencyCommissionAgencyType,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'AgencyCommission'), 'ALCommissionPercentage') AS ALAgencyCommissionPercentage,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'AgencyCommission'), 'APDCommissionPercentage') AS APDAgencyCommissionPercentage,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'AgencyCommission'), 'MTCCommissionPercentage') AS MTCAgencyCommissionPercentage,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'AgencyCommission'), 'TGLCommissionPercentage') AS TGLAgencyCommissionPercentage,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'AgencyCommission'), 'NTLCommissionPercentage') AS NTLAgencyCommissionPercentage,
        JSONExtractString(json, 'BillingType') AS SolartisInsuredV1BillingType,
        JSONExtractString(json, 'CancellationEffectiveDate') AS SolartisInsuredV1CancellationEffectiveDate,
        JSONExtractString(address, 'AddressCode') AS InsuredAddressAddressCode,
        JSONExtractString(address, 'AddressType') AS InsuredAddressAddressType,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'ApplicableDate') AS CommercialAutomobileApplicableDate,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'LastRateLookUpDate') AS CommercialAutomobileLastRateLookUpDate,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'ProductVersionNumber') AS CommercialAutomobileProductVersionNumber,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'ProductNumber') AS CommercialAutomobileProductNumber,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'State') AS CommercialAutomobileState,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'StreetNumberAddress1') AS CommercialAutomobileStreetNumberAddress1,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'StreetNameAddress2') AS CommercialAutomobileStreetNameAddress2,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'ZipCode1') AS CommercialAutomobileZipCode1,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Zipcode2') AS CommercialAutomobileZipcode2,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'City') AS CommercialAutomobileCity,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'County') AS CommercialAutomobileCounty,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'StateRegionCode') AS CommercialAutomobileStateRegionCode,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'StateRegion') AS CommercialAutomobileStateRegion,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'CountryCode') AS CommercialAutomobileCountryCode,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Country') AS CommercialAutomobileCountry,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'AcceptTRIA') AS AcceptTRIA,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TriaFactor') AS TriaFactor,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'ProratedPriorPremium') AS CommercialAutomobileProratedPriorPremium,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'WrittenPremium') AS CommercialAutomobileWrittenPremium,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'FullTermPremium') AS CommercialAutomobileFullTermPremium,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TrailerInterchangeLimit') AS CommercialAutomobileTrailerInterchangeLimit,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'PowerUnitsAndDriversDifference') AS PowerUnitsAndDriversDifference,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalPowerUnitsDifference') AS TotalPowerUnitsDifference,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'ExcludedOperation') AS ExcludedOperation,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'CoverageOnPolicyIndicator') AS MotorTruckCargoTrailerInterchangeCoverageCoverageOnPolicyIndicator,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'ProratedPriorPremium') AS MotorTruckCargoTrailerInterchangeCoverageProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'FullTermPremium') AS MotorTruckCargoTrailerInterchangeCoverageFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TriaPremium') AS TruckersGeneralLiabilityTriaPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'FinancialPerformance') AS TruckersGeneralLiabilityFinancialPerformance,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'DriverSelectionandTraining') AS TruckersGeneralLiabilityDriverSelectionandTraining,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'ManagementExperienceRiskManagement') AS TruckersGeneralLiabilityManagementExperienceRiskManagement,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'DriverRouteScore') AS TruckersGeneralLiabilityDriverRouteScore,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'DriverBehaviorScore') AS TruckersGeneralLiabilityDriverBehaviorScore,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'ScheduleRatingMod') AS TruckersGeneralLiabilityScheduleRatingMod,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'FinancialPerformanceReason') AS TruckersGeneralLiabilityFinancialPerformanceReason,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'DriverSelectionandTrainingReason') AS TruckersGeneralLiabilityDriverSelectionandTrainingReason,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'ManagementExperienceRiskManagementReason') AS TruckersGeneralLiabilityManagementExperienceRiskManagementReason,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'DriverRouteScoreReason') AS TruckersGeneralLiabilityDriverRouteScoreReason,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'DriverBehaviorScoreReason') AS TruckersGeneralLiabilityDriverBehaviorScoreReason,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'EarnedFeesAndTax') AS TruckersGeneralLiabilityEarnedFeesAndTax,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'UnearnedFeesAndTax') AS TruckersGeneralLiabilityUnearnedFeesAndTax,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'TriaPremium') AS NonTruckingLiabilityTriaPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'FinancialPerformance') AS NonTruckingLiabilityFinancialPerformance,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'DriverSelectionandTraining') AS NonTruckingLiabilityDriverSelectionandTraining,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'ManagementExperienceRiskManagement') AS NonTruckingLiabilityManagementExperienceRiskManagement,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'DriverRouteScore') AS NonTruckingLiabilityDriverRouteScore,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'DriverBehaviorScore') AS NonTruckingLiabilityDriverBehaviorScore,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'ScheduleRatingMod') AS NonTruckingLiabilityScheduleRatingMod,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'FinancialPerformanceReason') AS NonTruckingLiabilityFinancialPerformanceReason,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'DriverSelectionandTrainingReason') AS NonTruckingLiabilityDriverSelectionandTrainingReason,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'ManagementExperienceRiskManagementReason') AS NonTruckingLiabilityManagementExperienceRiskManagementReason,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'DriverRouteScoreReason') AS NonTruckingLiabilityDriverRouteScoreReason,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'DriverBehaviorScoreReason') AS NonTruckingLiabilityDriverBehaviorScoreReason,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'EarnedFeesAndTax') AS NonTruckingLiabilityEarnedFeesAndTax,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'UnearnedFeesAndTax') AS NonTruckingLiabilityUnearnedFeesAndTax,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'CarrierName') AS MotorTruckCargoCarrierName,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TriaPremium') AS MotorTruckCargoTriaPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'FinancialPerformance') AS MotorTruckCargoFinancialPerformance,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'DriverSelectionandTraining') AS MotorTruckCargoDriverSelectionandTraining,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'ManagementExperienceRiskManagement') AS MotorTruckCargoManagementExperienceRiskManagement,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'DriverRouteScore') AS MotorTruckCargoDriverRouteScore,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'DriverBehaviorScore') AS MotorTruckCargoDriverBehaviorScore,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'ScheduleRatingMod') AS MotorTruckCargoScheduleRatingMod,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'FinancialPerformanceReason') AS MotorTruckCargoFinancialPerformanceReason,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'DriverSelectionandTrainingReason') AS MotorTruckCargoDriverSelectionandTrainingReason,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'ManagementExperienceRiskManagementReason') AS MotorTruckCargoManagementExperienceRiskManagementReason,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'DriverRouteScoreReason') AS MotorTruckCargoDriverRouteScoreReason,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'DriverBehaviorScoreReason') AS MotorTruckCargoDriverBehaviorScoreReason,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'EarnedFeesAndTax') AS MotorTruckCargoEarnedFeesAndTax,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'UnearnedFeesAndTax') AS MotorTruckCargoUnearnedFeesAndTax,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'Losses'), 'TotalNumberOfClaims') AS NonTruckingLiabilityLossesTotalNumberOfClaims,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'Losses'), 'LossRatioThreshold') AS NonTruckingLiabilityLossesLossRatioThreshold,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'Losses'), 'TotalLossRatioThreshold') AS NonTruckingLiabilityLossesTotalLossRatioThreshold,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Losses'), 'TotalNumberOfClaims') AS MotorTruckCargoLossesTotalNumberOfClaims,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Losses'), 'LossRatioThreshold') AS MotorTruckCargoLossesLossRatioThreshold,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Losses'), 'TotalLossRatioThreshold') AS MotorTruckCargoLossesTotalLossRatioThreshold,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'Losses'), 'TotalNumberOfClaims') AS TruckersGeneralLiabilityLossesTotalNumberOfClaims,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'Losses'), 'LossRatioThreshold') AS TruckersGeneralLiabilityLossesLossRatioThreshold,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'Losses'), 'TotalLossRatioThreshold') AS TruckersGeneralLiabilityLossesTotalLossRatioThreshold,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'PremiumFinanceProviderName') AS PremiumFinancePremiumFinanceProviderName,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'OverridePremiumFinanceProvider') AS OverridePremiumFinanceProvider,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'OverrideFinanceType') AS OverrideFinanceType,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'FinancingOption') AS FinancingOption,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'FinancingType') AS PremiumFinanceFinancingType,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'ExternalQuoteId') AS ExternalQuoteId,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'ExternalQuoteNumber') AS ExternalQuoteNumber,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'Downpaymentamount') AS Downpaymentamount,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'TotalPaymentAmount') AS TotalPaymentAmount,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'NumberOfPayments') AS NumberOfPayments,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'InterestRate') AS InterestRate,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'InterestAmount') AS InterestAmount,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'TotalPremium') AS PremiumFinanceTotalPremium,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'AmountFinanced') AS AmountFinanced,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'FinanceCharge') AS FinanceCharge,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'LateDays') AS LateDays,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'LateCharge') AS LateCharge,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'LoanID') AS LoanID,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'PremiumFinanceProviderID') AS PremiumFinanceProviderID,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'PremiumFinanceProvider') AS PremiumFinanceProvider,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'ProviderAbbreviation') AS ProviderAbbreviation,
        JSONExtractString(JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'Provider'), 'LotteryWeight') AS LotteryWeight,
        JSONExtractString(JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'Provider'), 'LotteryWeightNewBusiness') AS LotteryWeightNewBusiness,
        JSONExtractString(json, 'CancellationDate') AS SolartisInsuredV1CancellationDate,
        JSONExtractString(json, 'CancellationType') AS SolartisInsuredV1CancellationType,
        JSONExtractString(json, 'CancellationReason') AS SolartisInsuredV1CancellationReason,
        JSONExtractString(json, 'EndorsementEffectiveDate') AS SolartisInsuredV1EndorsementEffectiveDate,
        JSONExtractString(insured, 'EndorsementEffectiveDate') AS InsuredEndorsementEffectiveDate,
        JSONExtractString(insured, 'HasPriorCancellations') AS HasPriorCancellations,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'SublineName') AS CommercialAutomobileSublineName,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TransactionType') AS CommercialAutomobileTransactionType,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'FullAddress') AS CommercialAutomobileFullAddress,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalTaxAmount') AS CommercialAutomobileTotalTaxAmount,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalFeeAmount') AS CommercialAutomobileTotalFeeAmount,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalSurchargeAmount') AS CommercialAutomobileTotalSurchargeAmount,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'BrokerOrServiceFee') AS CommercialAutomobileBrokerOrServiceFee,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MVROverride') AS CommercialAutomobileMVROverride,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TowingStorageAndLaborLimit') AS CommercialAutomobileTowingStorageAndLaborLimit,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'PriorChargedPremium') AS CommercialAutomobilePriorChargedPremium,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalLossCount') AS TotalLossCount,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TotalLossRatio') AS TotalLossRatio,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'ALPolicyFeeOverride') AS CommercialAutomobileALPolicyFeeOverride,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'ALUWFeeOverride') AS CommercialAutomobileALUWFeeOverride,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'APDPolicyFeeOverride') AS CommercialAutomobileAPDPolicyFeeOverride,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'APDUWFeeOverride') AS CommercialAutomobileAPDUWFeeOverride,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TGLPolicyFeeOverride') AS CommercialAutomobileTGLPolicyFeeOverride,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TGLUWFeeOverride') AS CommercialAutomobileTGLUWFeeOverride,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NTLPolicyFeeOverride') AS CommercialAutomobileNTLPolicyFeeOverride,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NTLUWFeeOverride') AS CommercialAutomobileNTLUWFeeOverride,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MTCPolicyFeeOverride') AS CommercialAutomobileMTCPolicyFeeOverride,
        JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MTCUWFeeOverride') AS CommercialAutomobileMTCUWFeeOverride,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'CoverageStartDate') AS OperationsCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'ChangeEffectiveDate') AS OperationsChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'CoverageStopDate') AS OperationsCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'WaivedOffPremium') AS OperationsWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'ChangeType') AS OperationsChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'WrittenPremium') AS OperationsWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'PriorChargedPremium') AS OperationsPriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'VehiclePersonalUse') AS VehiclePersonalUse,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Operations'), 'UIIAExposure') AS UIIAExposure,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'PriorChargedPremium') AS TruckersGeneralLiabilityCoveragePriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'CoverageStartDate') AS TruckersGeneralLiabilityCoverageCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'ChangeEffectiveDate') AS TruckersGeneralLiabilityCoverageChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'CoverageStopDate') AS TruckersGeneralLiabilityCoverageCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'PriorChargedPremium') AS NonTruckingLiabilityCoveragePriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'CoverageStartDate') AS NonTruckingLiabilityCoverageCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'ChangeEffectiveDate') AS NonTruckingLiabilityCoverageChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'CoverageStopDate') AS NonTruckingLiabilityCoverageCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'PriorChargedPremium') AS MotorTruckCargoCoveragePriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'CoverageStartDate') AS MotorTruckCargoCoverageCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'ChangeEffectiveDate') AS MotorTruckCargoCoverageChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'CoverageStopDate') AS MotorTruckCargoCoverageCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'WrittenPremium') AS TrailerInterchangeCoverageWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'PriorChargedPremium') AS MotorTruckCargoTrailerInterchangeCoveragePriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'WaivedOffPremium') AS MotorTruckCargoTrailerInterchangeCoverageWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'TotalWaivedOffPremium') AS MotorTruckCargoTrailerInterchangeCoverageTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'CoverageStartDate') AS MotorTruckCargoTrailerInterchangeCoverageCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'ChangeEffectiveDate') AS MotorTruckCargoTrailerInterchangeCoverageChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'CoverageStopDate') AS MotorTruckCargoTrailerInterchangeCoverageCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TrailerInterchangeCoverage'), 'ChangeType') AS MotorTruckCargoTrailerInterchangeCoverageChangeType,
        NULL AS TruckersGeneralLiabilityEntityName,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'SublineName') AS TruckersGeneralLiabilitySublineName,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TotalSurchargeAmount') AS TruckersGeneralLiabilityTotalSurchargeAmount,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'CoverageStartDate') AS TruckersGeneralLiabilityChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'CoverageStopDate') AS TruckersGeneralLiabilityCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'PriorChargedPremium') AS TruckersGeneralLiabilityPriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TGLAgencyCommissionOverride') AS TGLAgencyCommissionOverride,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TGLPremiumOverride') AS TGLPremiumOverride,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TGLPolicyFeeOverride') AS TruckersGeneralLiabilityTGLPolicyFeeOverride,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TGLUWFeeOverride') AS TruckersGeneralLiabilityTGLUWFeeOverride,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'TotalSurchargeAmount') AS NonTruckingLiabilityTotalSurchargeAmount,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'CoverageStartDate') AS NonTruckingLiabilityCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'ChangeEffectiveDate') AS NonTruckingLiabilityChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'CoverageStopDate') AS NonTruckingLiabilityCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'PriorChargedPremium') AS NonTruckingLiabilityPriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NTLAgencyCommissionOverride') AS NTLAgencyCommissionOverride,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NTLPremiumOverride') AS NTLPremiumOverride,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NTLPolicyFeeOverride') AS NonTruckingLiabilityNTLPolicyFeeOverride,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NTLUWFeeOverride') AS NonTruckingLiabilityNTLUWFeeOverride,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'TotalSurchargeAmount') AS MotorTruckCargoTotalSurchargeAmount,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'CoverageStartDate') AS MotorTruckCargoCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'ChangeEffectiveDate') AS MotorTruckCargoChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'CoverageStopDate') AS MotorTruckCargoCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'PriorChargedPremium') AS MotorTruckCargoPriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MTCAgencyCommissionOverride') AS MTCAgencyCommissionOverride,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MTCPremiumOverride') AS MTCPremiumOverride,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MTCPolicyFeeOverride') AS MotorTruckCargoMTCPolicyFeeOverride,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MTCUWFeeOverride') AS MotorTruckCargoMTCUWFeeOverride,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'Losses'), 'CoverageStartDate') AS NonTruckingLiabilityLossesCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'Losses'), 'ChangeEffectiveDate') AS NonTruckingLiabilityLossesChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'Losses'), 'CoverageStopDate') AS NonTruckingLiabilityLossesCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'Losses'), 'ChangeType') AS NonTruckingLiabilityLossesChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Losses'), 'CoverageStartDate') AS MotorTruckCargoLossesCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Losses'), 'ChangeEffectiveDate') AS MotorTruckCargoLossesChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Losses'), 'CoverageStopDate') AS MotorTruckCargoLossesCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'Losses'), 'ChangeType') AS MotorTruckCargoLossesChangeType,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'Losses'), 'CoverageStartDate') AS TruckersGeneralLiabilityLossesCoverageStartDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'Losses'), 'ChangeEffectiveDate') AS TruckersGeneralLiabilityLossesChangeEffectiveDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'Losses'), 'CoverageStopDate') AS TruckersGeneralLiabilityLossesCoverageStopDate,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'Losses'), 'ChangeType') AS TruckersGeneralLiabilityLossesChangeType,
        NULL AS CommoditiesPercentageOfHauls,
        JSONExtractString(JSONExtractString(insured, 'RetailAgent'), 'RetailAgentFirstName') AS RetailAgentFirstName,
        JSONExtractString(JSONExtractString(insured, 'RetailAgent'), 'RetailAgentLastName') AS RetailAgentLastName,
        JSONExtractString(JSONExtractString(insured, 'RetailAgent'), 'RetailAgentAssociatedAgency') AS RetailAgentAssociatedAgency,
        JSONExtractString(JSONExtractString(insured, 'RetailAgent'), 'RetailAgentAddress') AS RetailAgentAddress,
        JSONExtractString(JSONExtractString(insured, 'RetailAgent'), 'RetailAgentState') AS RetailAgentState,
        JSONExtractString(JSONExtractString(insured, 'RetailAgent'), 'RetailAgentCity') AS RetailAgentCity,
        JSONExtractString(JSONExtractString(insured, 'RetailAgent'), 'RetailAgentZip') AS RetailAgentZip,
        JSONExtractString(JSONExtractString(insured, 'RetailAgent'), 'RetailAgentPhoneNumber') AS RetailAgentPhoneNumber,
        JSONExtractString(JSONExtractString(insured, 'RetailAgent'), 'RetailAgentEmail') AS RetailAgentEmail,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'PFCQuoteNumber') AS PFCQuoteNumber,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'PFCContractNumber') AS PFCContractNumber,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Telematics'), 'DashCamAddress'), 'DashCamShippingAddress') AS DashCamShippingAddress,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Telematics'), 'DashCamAddress'), 'AddressType') AS DashCamAddressAddressType,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Telematics'), 'DashCamAddress'), 'StreetNumberAddress1') AS DashCamAddressStreetNumberAddress1,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Telematics'), 'DashCamAddress'), 'StreetNameAddress2') AS DashCamAddressStreetNameAddress2,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Telematics'), 'DashCamAddress'), 'City') AS DashCamAddressCity,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Telematics'), 'DashCamAddress'), 'County') AS DashCamAddressCounty,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Telematics'), 'DashCamAddress'), 'StateRegionCode') AS DashCamAddressStateRegionCode,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Telematics'), 'DashCamAddress'), 'StateRegion') AS DashCamAddressStateRegion,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Telematics'), 'DashCamAddress'), 'ZipCode1') AS DashCamAddressZipCode1,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Telematics'), 'DashCamAddress'), 'Zipcode2') AS DashCamAddressZipcode2,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Telematics'), 'DashCamAddress'), 'CountryCode') AS DashCamAddressCountryCode,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Telematics'), 'DashCamAddress'), 'Country') AS DashCamAddressCountry,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'Telematics'), 'TelematicsType') AS TelematicsType,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'IsPremiumOverridden') AS TruckersGeneralLiabilityIsPremiumOverridden,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'IsPremiumOverridden') AS NonTruckingLiabilityIsPremiumOverridden,
        JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'IsPremiumOverridden') AS MotorTruckCargoIsPremiumOverridden,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'PFProviderTypeCode') AS PFProviderTypeCode,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'IsPremiumFinanceProviderEnabled') AS IsPremiumFinanceProviderEnabled,
        JSONExtractString(JSONExtractString(json, 'PremiumFinance'), 'PremiumFinanceProviderName') AS PremiumFinanceProviderName,
        JSONExtractString(json, 'UniversalUniqueIdentifier') AS UniversalUniqueIdentifier,
        JSONExtractString(insured, 'IdentificationType') AS IdentificationType,
        JSONExtractString(address, 'OverrideAddress') AS OverrideAddress,
        JSONExtractString(address, 'OverridenBy') AS OverridenBy,
        JSONExtractString(address, 'OverridenIPAddress') AS OverridenIPAddress,
        JSONExtractString(address, 'OverridenDate') AS OverridenDate,
        JSONExtractString(json, 'OverrideCarrierLottery') AS OverrideCarrierLottery,
        JSONExtractString(json, 'OverrideEligibilityRules') AS OverrideEligibilityRules,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'WrittenPremium') AS MotorTruckCargoCoverageWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'FullTermPremium') AS MotorTruckCargoCoverageFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'ProratedPriorPremium') AS MotorTruckCargoCoverageProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'WaivedOffPremium') AS MotorTruckCargoCoverageWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'TotalWaivedOffPremium') AS MotorTruckCargoCoverageTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'WrittenPremium') AS NonTruckingLiabilityCoverageWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'WrittenPremium') AS TruckersGeneralLiabilityCoverageWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'FullTermPremium') AS NonTruckingLiabilityCoverageFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'FullTermPremium') AS TruckersGeneralLiabilityCoverageFullTermPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'ProratedPriorPremium') AS NonTruckingLiabilityCoverageProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'ProratedPriorPremium') AS TruckersGeneralLiabilityCoverageProratedPriorPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'WaivedOffPremium') AS NonTruckingLiabilityCoverageWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'TotalWaivedOffPremium') AS NonTruckingLiabilityCoverageTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'WaivedOffPremium') AS TruckersGeneralLiabilityCoverageWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'TotalWaivedOffPremium') AS TruckersGeneralLiabilityCoverageTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'Losses'), 'WrittenPremium') AS NonTruckingLiabilityLossesWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'Losses'), 'WaivedOffPremium') AS NonTruckingLiabilityLossesWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'NonTruckingLiability'), 'NonTruckingLiabilityCoverage'), 'Losses'), 'TotalWaivedOffPremium') AS NonTruckingLiabilityLossesTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'Losses'), 'WrittenPremium') AS MotorTruckCargoLossesWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'Losses'), 'PriorChargedPremium') AS MotorTruckCargoLossesPriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'Losses'), 'WaivedOffPremium') AS MotorTruckCargoLossesWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'MotorTruckCargo'), 'MotorTruckCargoCoverage'), 'Losses'), 'TotalWaivedOffPremium') AS MotorTruckCargoLossesTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'Losses'), 'WrittenPremium') AS TruckersGeneralLiabilityLossesWrittenPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'Losses'), 'PriorChargedPremium') AS TruckersGeneralLiabilityLossesPriorChargedPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'Losses'), 'WaivedOffPremium') AS TruckersGeneralLiabilityLossesWaivedOffPremium,
        JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(JSONExtractString(insured, 'CommercialAutomobile'), 'TruckersGeneralLiability'), 'TruckersGeneralLiabilityCoverage'), 'Losses'), 'TotalWaivedOffPremium') AS TruckersGeneralLiabilityLossesTotalWaivedOffPremium
    FROM solartis_wip_submissions.raw_submissions
    ARRAY JOIN JSONExtractArrayRaw(JSONExtractString(json, 'Account'), 'Insured') AS insured
    ARRAY JOIN JSONExtractArrayRaw(insured, 'InsuredAddress') AS address
    ARRAY JOIN JSONExtractArrayRaw(insured, 'InsuredContact') as insured_contact
    ARRAY JOIN JSONExtractArrayRaw(insured_contact, 'InsuredContactCommunication') AS contact
);