CREATE VIEW if not exists solartis_wip_submissions.vehicles AS (
    SELECT 
        JSONExtractString(json, 'SubmissionNumber') AS SubmissionNumber,
        JSONExtractString(json, 'QuoteNumber') AS QuoteNumber,
        JSONExtractString(json, 'PolicyNumber') AS PolicyNumber,
        JSONExtractString(json, 'PolicySubNumber') AS PolicySubNumber,
        JSONExtractString(json, 'EndorsementNumber') AS EndorsementNumber,
        JSONExtractString(json, 'VehicleNumber') AS VehicleNumber,
        JSONExtractString(vehicle_schedule, 'GaragingLocationStreetNumberAddress1') AS GaragingLocationStreetNumberAddress1,
        JSONExtractString(vehicle_schedule, 'GaragingLocationStreetNameAddress2') AS GaragingLocationStreetNameAddress2,
        JSONExtractString(vehicle_schedule, 'GaragingLocationCity') AS GaragingLocationCity,
        JSONExtractString(vehicle_schedule, 'GaragingLocationStateRegion') AS GaragingLocationStateRegion,
        JSONExtractString(vehicle_schedule, 'GaragingLocationZipCode1') AS GaragingLocationZipCode1,
        JSONExtractString(vehicle_schedule, 'GaragingLocationCounty') AS GaragingLocationCounty,
        JSONExtractString(vehicle_schedule, 'GaragingLocationZipCode2') AS GaragingLocationZipCode2,
        JSONExtractString(vehicle_schedule, 'GaragingLocationStateRegionCode') AS GaragingLocationStateRegionCode,
        JSONExtractString(vehicle_schedule, 'GaragingLocationCountryCode') AS GaragingLocationCountryCode,
        JSONExtractString(vehicle_schedule, 'GaragingLocationCountry') AS GaragingLocationCountry,
        JSONExtractString(vehicle_schedule, 'VehicleValueCount') AS VehicleValueCount,
        JSONExtractString(vehicle_schedule, 'TotalVehicleValue') AS TotalVehicleValue,
        JSONExtractString(vehicle_schedule, 'VehicleScheduleTotalPremium') AS VehicleScheduleTotalPremium,
        JSONExtractString(vehicle_schedule, 'TrailerOwned') AS TrailerOwned,
        JSONExtractString(vehicle_schedule, 'TrailerNonOwned') AS TrailerNonOwned,
        JSONExtractString(vehicle_schedule, 'VehicleType') AS VehicleType,
        JSONExtractString(vehicle_schedule, 'VehicleValue') AS VehicleValue,
        JSONExtractString(vehicle_schedule, 'VehicleOperation') AS VehicleOperation,
        JSONExtractString(vehicle_schedule, 'VehicleClass') AS VehicleClass,
        JSONExtractString(vehicle_schedule, 'VehicleAge') AS VehicleAge,
        JSONExtractString(vehicle_schedule, 'VehicleDeductible') AS VehicleDeductible,
        JSONExtractString(vehicle_schedule, 'VehiclePremium') AS VehiclePremium,
        JSONExtractString(vehicle_schedule, 'Territory') AS Territory,
        JSONExtractString(vehicle_schedule, 'VehicleYear') AS VehicleYear,
        JSONExtractString(vehicle_schedule, 'BodyTypeClass') AS BodyTypeClass,
        JSONExtractString(vehicle_schedule, 'IsAPDSelected') AS IsAPDSelected,
        JSONExtractString(vehicle_schedule, 'Make') AS Make,
        JSONExtractString(vehicle_schedule, 'Model') AS Model,
        JSONExtractString(vehicle_schedule, 'VehicleIdentificationNumber') AS VehicleIdentificationNumber,
        JSONExtractString(vehicle_schedule, 'BusinessUseType') AS BusinessUseType,
        JSONExtractString(vehicle_schedule, 'Density') AS Density,
        JSONExtractString(vehicle_schedule, 'Cargo') AS Cargo,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'MinimumPremiumMidRangeFactor') AS AutoLiabilityBIPDCoverageRatesMinimumPremiumMidRangeFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'Radius1') AS AutoLiabilityBIPDCoverageRatesRadius1,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'Radius2') AS AutoLiabilityBIPDCoverageRatesRadius2,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'Radius3') AS AutoLiabilityBIPDCoverageRatesRadius3,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'Radius4') AS AutoLiabilityBIPDCoverageRatesRadius4,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'RadiusFactor1') AS AutoLiabilityBIPDCoverageRatesRadiusFactor1,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'RadiusFactor2') AS AutoLiabilityBIPDCoverageRatesRadiusFactor2,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'RadiusFactor3') AS AutoLiabilityBIPDCoverageRatesRadiusFactor3,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'RadiusFactor4') AS AutoLiabilityBIPDCoverageRatesRadiusFactor4,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'RadiusFactor') AS AutoLiabilityBIPDCoverageRatesRadiusFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'BaseRateBI') AS AutoLiabilityBIPDCoverageRatesBaseRateBI,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'BaseRatePD') AS AutoLiabilityBIPDCoverageRatesBaseRatePD,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'VehicleWeightClass') AS AutoLiabilityBIPDCoverageRatesVehicleWeightClass,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'ModelYearFactor') AS AutoLiabilityBIPDCoverageRatesModelYearFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'ALBIPDBaseRate') AS AutoLiabilityBIPDCoverageRatesALBIPDBaseRate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'RatedPremium') AS AutoLiabilityBIPDCoverageRatesRatedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'ModPremium') AS AutoLiabilityBIPDCoverageRatesModPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'MinimumPremium') AS AutoLiabilityBIPDCoverageRatesMinimumPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'FinalVehiclePremium') AS AutoLiabilityBIPDCoverageRatesFinalVehiclePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'Premium') AS AutoLiabilityBIPDCoverageRatesPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'WrittenPremium') AS AutoLiabilityBIPDCoverageRatesWrittenPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'ChangeType') AS AutoLiabilityBIPDCoverageRatesChangeType,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'FullTermPremium') AS AutoLiabilityBIPDCoverageRatesFullTermPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'ProratedPremium') AS AutoLiabilityBIPDCoverageRatesProratedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'ProratedPriorPremium') AS AutoLiabilityBIPDCoverageRatesProratedPriorPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'ChangeProrateFactor') AS AutoLiabilityBIPDCoverageRatesChangeProrateFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'ChangePremium') AS AutoLiabilityBIPDCoverageRatesChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'ProratedChangePremium') AS AutoLiabilityBIPDCoverageRatesProratedChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'WaivedOffPremium') AS AutoLiabilityBIPDCoverageRatesWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'TotalWaivedOffPremium') AS AutoLiabilityBIPDCoverageRatesTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'PremiumPriorToProrata') AS AutoLiabilityBIPDCoverageRatesPremiumPriorToProrata,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'BodyTypeBusinessClassFactorToUse') AS AutoLiabilityBIPDCoverageRatesBodyTypeBusinessClassFactorToUse,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'BodyTypeBusinessClassFactor') AS AutoLiabilityBIPDCoverageRatesBodyTypeBusinessClassFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'BodyTypeBusinessClassTrailerFactor') AS AutoLiabilityBIPDCoverageRatesBodyTypeBusinessClassTrailerFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'ILF') AS AutoLiabilityBIPDCoverageRatesILF,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'ILFTrailers') AS AutoLiabilityBIPDCoverageRatesILFTrailers,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'USDOTFactor') AS AutoLiabilityBIPDCoverageRatesUSDOTFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'TotalBaseRate') AS AutoLiabilityBIPDCoverageRatesTotalBaseRate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'BIPDILF') AS AutoLiabilityBIPDCoverageRatesBIPDILF,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'BIPDModelYear') AS AutoLiabilityBIPDCoverageRatesBIPDModelYear,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'ModelYearTrailerFactor') AS AutoLiabilityBIPDCoverageRatesModelYearTrailerFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'TotalRadiusTerritoryFactor') AS AutoLiabilityBIPDCoverageRatesTotalRadiusTerritoryFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'VehicleWeightClassFactor') AS AutoLiabilityBIPDCoverageRatesVehicleWeightClassFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'VehicleClassFactor') AS AutoLiabilityBIPDCoverageRatesVehicleClassFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'IncreasedLimitFactor') AS AutoLiabilityBIPDCoverageRatesIncreasedLimitFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'PopulationDensityFactor') AS AutoLiabilityBIPDCoverageRatesPopulationDensityFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'TotalMinimumPremium') AS AutoLiabilityBIPDCoverageRatesTotalMinimumPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'FinalPremium') AS AutoLiabilityBIPDCoverageRatesFinalPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'TotalPremium') AS AutoLiabilityBIPDCoverageRatesTotalPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'ILFTrailerFactor') AS AutoLiabilityBIPDCoverageRatesILFTrailerFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'Radius1') AS AutoLiabilityUMUIMCoverageRatesRadius1,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'Radius2') AS AutoLiabilityUMUIMCoverageRatesRadius2,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'Radius3') AS AutoLiabilityUMUIMCoverageRatesRadius3,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'Radius4') AS AutoLiabilityUMUIMCoverageRatesRadius4,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'RadiusFactor1') AS AutoLiabilityUMUIMCoverageRatesRadiusFactor1,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'RadiusFactor2') AS AutoLiabilityUMUIMCoverageRatesRadiusFactor2,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'RadiusFactor3') AS AutoLiabilityUMUIMCoverageRatesRadiusFactor3,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'RadiusFactor4') AS AutoLiabilityUMUIMCoverageRatesRadiusFactor4,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'RadiusFactor') AS AutoLiabilityUMUIMCoverageRatesRadiusFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'BaseRateUMUIM') AS AutoLiabilityUMUIMCoverageRatesBaseRateUMUIM,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'UMUIMILF') AS AutoLiabilityUMUIMCoverageRatesUMUIMILF,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'ModPremium') AS AutoLiabilityUMUIMCoverageRatesModPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'Premium') AS AutoLiabilityUMUIMCoverageRatesPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'WrittenPremium') AS AutoLiabilityUMUIMCoverageRatesWrittenPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'ChangeType') AS AutoLiabilityUMUIMCoverageRatesChangeType,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'FullTermPremium') AS AutoLiabilityUMUIMCoverageRatesFullTermPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'ProratedPremium') AS AutoLiabilityUMUIMCoverageRatesProratedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'ProratedPriorPremium') AS AutoLiabilityUMUIMCoverageRatesProratedPriorPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'ChangeProrateFactor') AS AutoLiabilityUMUIMCoverageRatesChangeProrateFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'ChangePremium') AS AutoLiabilityUMUIMCoverageRatesChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'ProratedChangePremium') AS AutoLiabilityUMUIMCoverageRatesProratedChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'WaivedOffPremium') AS AutoLiabilityUMUIMCoverageRatesWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'TotalWaivedOffPremium') AS AutoLiabilityUMUIMCoverageRatesTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'PremiumPriorToProrata') AS AutoLiabilityUMUIMCoverageRatesPremiumPriorToProrata,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'RatedPremium') AS AutoLiabilityUMUIMCoverageRatesRatedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'VehicleWeightClassFactor') AS AutoLiabilityUMUIMCoverageRatesVehicleWeightClassFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'TotalPremium') AS AutoLiabilityUMUIMCoverageRatesTotalPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'PostLossRatioFactor') AS AutoPhysicalDamageCoverageRatesPostLossRatioFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'BaseRateFactor') AS AutoPhysicalDamageCoverageRatesBaseRateFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'RateFactorClass') AS AutoPhysicalDamageCoverageRatesRateFactorClass,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'VehicleAgeFactor') AS AutoPhysicalDamageCoverageRatesVehicleAgeFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'VehicleRate') AS AutoPhysicalDamageCoverageRatesVehicleRate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'DeductibleFactor') AS AutoPhysicalDamageCoverageRatesDeductibleFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'PopulationDensityFactor') AS AutoPhysicalDamageCoverageRatesPopulationDensityFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'StateFactor') AS AutoPhysicalDamageCoverageRatesStateFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'RateToUse') AS AutoPhysicalDamageCoverageRatesRateToUse,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'PurePremium') AS AutoPhysicalDamageCoverageRatesPurePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'ModifiedVehiclePremium') AS AutoPhysicalDamageCoverageRatesModifiedVehiclePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'Premium') AS AutoPhysicalDamageCoverageRatesPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'WrittenPremium') AS AutoPhysicalDamageCoverageRatesWrittenPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'ChangeType') AS AutoPhysicalDamageCoverageRatesChangeType,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'FullTermPremium') AS AutoPhysicalDamageCoverageRatesFullTermPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'ProratedPremium') AS AutoPhysicalDamageCoverageRatesProratedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'ProratedPriorPremium') AS AutoPhysicalDamageCoverageRatesProratedPriorPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'ChangeProrateFactor') AS AutoPhysicalDamageCoverageRatesChangeProrateFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'ChangePremium') AS AutoPhysicalDamageCoverageRatesChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'ProratedChangePremium') AS AutoPhysicalDamageCoverageRatesProratedChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'WaivedOffPremium') AS AutoPhysicalDamageCoverageRatesWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'TotalWaivedOffPremium') AS AutoPhysicalDamageCoverageRatesTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'PremiumPriorToProrata') AS AutoPhysicalDamageCoverageRatesPremiumPriorToProrata,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'PostLossRatioPremium') AS AutoPhysicalDamageCoverageRatesPostLossRatioPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'DeductibleCode') AS AutoPhysicalDamageCoverageRatesDeductibleCode,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'WeightPercent') AS AutoPhysicalDamageCoverageRatesWeightPercent,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'WeightedRate') AS AutoPhysicalDamageCoverageRatesWeightedRate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'Premium') AS HiredNonOwnedAutoCoverageRatesPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'WrittenPremium') AS HiredNonOwnedAutoCoverageRatesWrittenPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'ChangeType') AS HiredNonOwnedAutoCoverageRatesChangeType,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'FullTermPremium') AS HiredNonOwnedAutoCoverageRatesFullTermPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'ProratedPremium') AS HiredNonOwnedAutoCoverageRatesProratedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'ProratedPriorPremium') AS HiredNonOwnedAutoCoverageRatesProratedPriorPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'ChangeProrateFactor') AS HiredNonOwnedAutoCoverageRatesChangeProrateFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'ChangePremium') AS HiredNonOwnedAutoCoverageRatesChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'ProratedChangePremium') AS HiredNonOwnedAutoCoverageRatesProratedChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'WaivedOffPremium') AS HiredNonOwnedAutoCoverageRatesWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'TotalWaivedOffPremium') AS HiredNonOwnedAutoCoverageRatesTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'PremiumPriorToProrata') AS HiredNonOwnedAutoCoverageRatesPremiumPriorToProrata,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'BaseRateHNOA') AS HiredNonOwnedAutoCoverageRatesBaseRateHNOA,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'HNOAILF') AS HiredNonOwnedAutoCoverageRatesHNOAILF,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'RatedPremium') AS HiredNonOwnedAutoCoverageRatesRatedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'HNOACoveragePremium') AS HiredNonOwnedAutoCoverageRatesHNOACoveragePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'HNOACoverageRate') AS HiredNonOwnedAutoCoverageRatesHNOACoverageRate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'TotalPremium') AS HiredNonOwnedAutoCoverageRatesTotalPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'RadiusFactor1') AS MedicalPaymentsCoverageRatesRadiusFactor1,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'RadiusFactor2') AS MedicalPaymentsCoverageRatesRadiusFactor2,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'RadiusFactor3') AS MedicalPaymentsCoverageRatesRadiusFactor3,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'RadiusFactor4') AS MedicalPaymentsCoverageRatesRadiusFactor4,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'Radius1') AS MedicalPaymentsCoverageRatesRadius1,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'Radius2') AS MedicalPaymentsCoverageRatesRadius2,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'Radius3') AS MedicalPaymentsCoverageRatesRadius3,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'Radius4') AS MedicalPaymentsCoverageRatesRadius4,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'RadiusFactor') AS MedicalPaymentsCoverageRatesRadiusFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'BaseRateMedPay') AS MedicalPaymentsCoverageRatesBaseRateMedPay,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'VehicleWeightClassFactor') AS MedicalPaymentsCoverageRatesVehicleWeightClassFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'MedPayModelYearFactor') AS MedicalPaymentsCoverageRatesMedPayModelYearFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'MedPayILF') AS MedicalPaymentsCoverageRatesMedPayILF,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'RatedPremium') AS MedicalPaymentsCoverageRatesRatedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'ModPremium') AS MedicalPaymentsCoverageRatesModPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'MedPayCoverageFactor') AS MedicalPaymentsCoverageRatesMedPayCoverageFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'MedPayState') AS MedicalPaymentsCoverageRatesMedPayState,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'MedPayCovered') AS MedicalPaymentsCoverageRatesMedPayCovered,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'MedPayEligiblity') AS MedicalPaymentsCoverageRatesMedPayEligiblity,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'TotalMedPay') AS MedicalPaymentsCoverageRatesTotalMedPay,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'Premium') AS MedicalPaymentsCoverageRatesPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'WrittenPremium') AS MedicalPaymentsCoverageRatesWrittenPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'ChangeType') AS MedicalPaymentsCoverageRatesChangeType,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'FullTermPremium') AS MedicalPaymentsCoverageRatesFullTermPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'ProratedPremium') AS MedicalPaymentsCoverageRatesProratedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'ProratedPriorPremium') AS MedicalPaymentsCoverageRatesProratedPriorPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'ChangeProrateFactor') AS MedicalPaymentsCoverageRatesChangeProrateFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'ChangePremium') AS MedicalPaymentsCoverageRatesChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'ProratedChangePremium') AS MedicalPaymentsCoverageRatesProratedChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'WaivedOffPremium') AS MedicalPaymentsCoverageRatesWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'TotalWaivedOffPremium') AS MedicalPaymentsCoverageRatesTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'PremiumPriorToProrata') AS MedicalPaymentsCoverageRatesPremiumPriorToProrata,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'BodyTypeBusinessClassVehicleFactor') AS MedicalPaymentsCoverageRatesBodyTypeBusinessClassVehicleFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'BodyTypeBusinessClassFactor') AS MedicalPaymentsCoverageRatesBodyTypeBusinessClassFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'BodyTypeBusinessClassTrailerFactor') AS MedicalPaymentsCoverageRatesBodyTypeBusinessClassTrailerFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'MedPayModelYear') AS MedicalPaymentsCoverageRatesMedPayModelYear,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'ModelYearTrailerFactor') AS MedicalPaymentsCoverageRatesModelYearTrailerFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'ModelYearFactor') AS MedicalPaymentsCoverageRatesModelYearFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'MedPayCoverageRate') AS MedicalPaymentsCoverageRatesMedPayCoverageRate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'USDOTViolationsFactor') AS MedicalPaymentsCoverageRatesUSDOTViolationsFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'USDOTBasicViolationsFactor') AS MedicalPaymentsCoverageRatesUSDOTBasicViolationsFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'USDOTFactor') AS MedicalPaymentsCoverageRatesUSDOTFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'TotalPremium') AS MedicalPaymentsCoverageRatesTotalPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'Radius1') AS PersonalInjuryProtectionCoverageRatesRadius1,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'Radius2') AS PersonalInjuryProtectionCoverageRatesRadius2,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'Radius3') AS PersonalInjuryProtectionCoverageRatesRadius3,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'Radius4') AS PersonalInjuryProtectionCoverageRatesRadius4,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'RadiusFactor1') AS PersonalInjuryProtectionCoverageRatesRadiusFactor1,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'RadiusFactor2') AS PersonalInjuryProtectionCoverageRatesRadiusFactor2,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'RadiusFactor3') AS PersonalInjuryProtectionCoverageRatesRadiusFactor3,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'RadiusFactor4') AS PersonalInjuryProtectionCoverageRatesRadiusFactor4,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'RadiusFactor') AS PersonalInjuryProtectionCoverageRatesRadiusFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'PIPCoverageFactor') AS PersonalInjuryProtectionCoverageRatesPIPCoverageFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'PIPState') AS PersonalInjuryProtectionCoverageRatesPIPState,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'PIPCovered') AS PersonalInjuryProtectionCoverageRatesPIPCovered,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'PIPEligiblity') AS PersonalInjuryProtectionCoverageRatesPIPEligiblity,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'TotalPIP') AS PersonalInjuryProtectionCoverageRatesTotalPIP,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'Premium') AS PersonalInjuryProtectionCoverageRatesPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'WrittenPremium') AS PersonalInjuryProtectionCoverageRatesWrittenPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'ChangeType') AS PersonalInjuryProtectionCoverageRatesChangeType,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'FullTermPremium') AS PersonalInjuryProtectionCoverageRatesFullTermPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'ProratedPremium') AS PersonalInjuryProtectionCoverageRatesProratedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'ProratedPriorPremium') AS PersonalInjuryProtectionCoverageRatesProratedPriorPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'ChangeProrateFactor') AS PersonalInjuryProtectionCoverageRatesChangeProrateFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'ChangePremium') AS PersonalInjuryProtectionCoverageRatesChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'ProratedChangePremium') AS PersonalInjuryProtectionCoverageRatesProratedChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'WaivedOffPremium') AS PersonalInjuryProtectionCoverageRatesWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'TotalWaivedOffPremium') AS PersonalInjuryProtectionCoverageRatesTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'PremiumPriorToProrata') AS PersonalInjuryProtectionCoverageRatesPremiumPriorToProrata,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'BaseRatePIP') AS PersonalInjuryProtectionCoverageRatesBaseRatePIP,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'BodyTypeBusinessClassVehicleFactor') AS PersonalInjuryProtectionCoverageRatesBodyTypeBusinessClassVehicleFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'BodyTypeBusinessClassFactor') AS PersonalInjuryProtectionCoverageRatesBodyTypeBusinessClassFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'BodyTypeBusinessClassTrailerFactor') AS PersonalInjuryProtectionCoverageRatesBodyTypeBusinessClassTrailerFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'RatedPremium') AS PersonalInjuryProtectionCoverageRatesRatedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'PIPModelYear') AS PersonalInjuryProtectionCoverageRatesPIPModelYear,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'ModelYearTrailerFactor') AS PersonalInjuryProtectionCoverageRatesModelYearTrailerFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'ModelYearFactor') AS PersonalInjuryProtectionCoverageRatesModelYearFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'PIPCoveragePremium') AS PersonalInjuryProtectionCoverageRatesPIPCoveragePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'PIPCoverageRate') AS PersonalInjuryProtectionCoverageRatesPIPCoverageRate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'USDOTViolationsFactor') AS PersonalInjuryProtectionCoverageRatesUSDOTViolationsFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'USDOTBasicViolationsFactor') AS PersonalInjuryProtectionCoverageRatesUSDOTBasicViolationsFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'USDOTFactor') AS PersonalInjuryProtectionCoverageRatesUSDOTFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'TotalPremium') AS PersonalInjuryProtectionCoverageRatesTotalPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TowingStorageAndLaborCoverageRates'), 'VehicleValueGreaterThanZero') AS TowingStorageAndLaborCoverageRatesVehicleValueGreaterThanZero,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TowingStorageAndLaborCoverageRates'), 'VehicleRate') AS TowingStorageAndLaborCoverageRatesVehicleRate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TowingStorageAndLaborCoverageRates'), 'WrittenPremium') AS TowingStorageAndLaborCoverageRatesWrittenPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TowingStorageAndLaborCoverageRates'), 'ChangeType') AS TowingStorageAndLaborCoverageRatesChangeType,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TowingStorageAndLaborCoverageRates'), 'FullTermPremium') AS TowingStorageAndLaborCoverageRatesFullTermPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TowingStorageAndLaborCoverageRates'), 'ProratedPremium') AS TowingStorageAndLaborCoverageRatesProratedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TowingStorageAndLaborCoverageRates'), 'ProratedPriorPremium') AS TowingStorageAndLaborCoverageRatesProratedPriorPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TowingStorageAndLaborCoverageRates'), 'ChangeProrateFactor') AS TowingStorageAndLaborCoverageRatesChangeProrateFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TowingStorageAndLaborCoverageRates'), 'ChangePremium') AS TowingStorageAndLaborCoverageRatesChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TowingStorageAndLaborCoverageRates'), 'ProratedChangePremium') AS TowingStorageAndLaborCoverageRatesProratedChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TowingStorageAndLaborCoverageRates'), 'WaivedOffPremium') AS TowingStorageAndLaborCoverageRatesWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TowingStorageAndLaborCoverageRates'), 'TotalWaivedOffPremium') AS TowingStorageAndLaborCoverageRatesTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TowingStorageAndLaborCoverageRates'), 'Premium') AS TowingStorageAndLaborCoverageRatesPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TowingStorageAndLaborCoverageRates'), 'PremiumPriorToProrata') AS TowingStorageAndLaborCoverageRatesPremiumPriorToProrata,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TowingStorageAndLaborCoverageRates'), 'TotalPremium') AS TowingStorageAndLaborCoverageRatesTotalPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TrailerInterchangeCoverageRates'), 'WrittenPremium') AS TrailerInterchangeCoverageRatesWrittenPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TrailerInterchangeCoverageRates'), 'ChangeType') AS TrailerInterchangeCoverageRatesChangeType,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TrailerInterchangeCoverageRates'), 'FullTermPremium') AS TrailerInterchangeCoverageRatesFullTermPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TrailerInterchangeCoverageRates'), 'ProratedPremium') AS TrailerInterchangeCoverageRatesProratedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TrailerInterchangeCoverageRates'), 'ProratedPriorPremium') AS TrailerInterchangeCoverageRatesProratedPriorPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TrailerInterchangeCoverageRates'), 'ChangeProrateFactor') AS TrailerInterchangeCoverageRatesChangeProrateFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TrailerInterchangeCoverageRates'), 'ChangePremium') AS TrailerInterchangeCoverageRatesChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TrailerInterchangeCoverageRates'), 'ProratedChangePremium') AS TrailerInterchangeCoverageRatesProratedChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TrailerInterchangeCoverageRates'), 'WaivedOffPremium') AS TrailerInterchangeCoverageRatesWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TrailerInterchangeCoverageRates'), 'TotalWaivedOffPremium') AS TrailerInterchangeCoverageRatesTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TrailerInterchangeCoverageRates'), 'Premium') AS TrailerInterchangeCoverageRatesPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TrailerInterchangeCoverageRates'), 'PremiumPriorToProrata') AS TrailerInterchangeCoverageRatesPremiumPriorToProrata,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TrailerInterchangeCoverageRates'), 'TotalPremium') AS TrailerInterchangeCoverageRatesTotalPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'Radius1') AS UnderinsuredBodilyInjuryCoverageRatesRadius1,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'Radius2') AS UnderinsuredBodilyInjuryCoverageRatesRadius2,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'Radius3') AS UnderinsuredBodilyInjuryCoverageRatesRadius3,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'Radius4') AS UnderinsuredBodilyInjuryCoverageRatesRadius4,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'RadiusFactor1') AS UnderinsuredBodilyInjuryCoverageRatesRadiusFactor1,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'RadiusFactor2') AS UnderinsuredBodilyInjuryCoverageRatesRadiusFactor2,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'RadiusFactor3') AS UnderinsuredBodilyInjuryCoverageRatesRadiusFactor3,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'RadiusFactor4') AS UnderinsuredBodilyInjuryCoverageRatesRadiusFactor4,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'RadiusFactor') AS UnderinsuredBodilyInjuryCoverageRatesRadiusFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'UIMBICoverageFactor') AS UnderinsuredBodilyInjuryCoverageRatesUIMBICoverageFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'UIMBIState') AS UnderinsuredBodilyInjuryCoverageRatesUIMBIState,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'UIMBICovered') AS UnderinsuredBodilyInjuryCoverageRatesUIMBICovered,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'UIMBIEligiblity') AS UnderinsuredBodilyInjuryCoverageRatesUIMBIEligiblity,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'TotalUIMBI') AS UnderinsuredBodilyInjuryCoverageRatesTotalUIMBI,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'Premium') AS UnderinsuredBodilyInjuryCoverageRatesPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'WrittenPremium') AS UnderinsuredBodilyInjuryCoverageRatesWrittenPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'ChangeType') AS UnderinsuredBodilyInjuryCoverageRatesChangeType,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'FullTermPremium') AS UnderinsuredBodilyInjuryCoverageRatesFullTermPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'ProratedPremium') AS UnderinsuredBodilyInjuryCoverageRatesProratedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'ProratedPriorPremium') AS UnderinsuredBodilyInjuryCoverageRatesProratedPriorPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'ChangeProrateFactor') AS UnderinsuredBodilyInjuryCoverageRatesChangeProrateFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'ChangePremium') AS UnderinsuredBodilyInjuryCoverageRatesChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'ProratedChangePremium') AS UnderinsuredBodilyInjuryCoverageRatesProratedChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'WaivedOffPremium') AS UnderinsuredBodilyInjuryCoverageRatesWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'TotalWaivedOffPremium') AS UnderinsuredBodilyInjuryCoverageRatesTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'PremiumPriorToProrata') AS UnderinsuredBodilyInjuryCoverageRatesPremiumPriorToProrata,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'BaseRateUIMBI') AS UnderinsuredBodilyInjuryCoverageRatesBaseRateUIMBI,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'BodyTypeBusinessClassVehicleFactor') AS UnderinsuredBodilyInjuryCoverageRatesBodyTypeBusinessClassVehicleFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'BodyTypeBusinessClassFactor') AS UnderinsuredBodilyInjuryCoverageRatesBodyTypeBusinessClassFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'BodyTypeBusinessClassTrailerFactor') AS UnderinsuredBodilyInjuryCoverageRatesBodyTypeBusinessClassTrailerFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'RatedPremium') AS UnderinsuredBodilyInjuryCoverageRatesRatedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'UIMBICoveragePremium') AS UnderinsuredBodilyInjuryCoverageRatesUIMBICoveragePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'UIMBICoverageRate') AS UnderinsuredBodilyInjuryCoverageRatesUIMBICoverageRate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'USDOTViolationsFactor') AS UnderinsuredBodilyInjuryCoverageRatesUSDOTViolationsFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'USDOTBasicViolationsFactor') AS UnderinsuredBodilyInjuryCoverageRatesUSDOTBasicViolationsFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'TotalPremium') AS UnderinsuredBodilyInjuryCoverageRatesTotalPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'UIMPDCoverageFactor') AS UnderinsuredPropertyDamageCoverageRatesUIMPDCoverageFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'UIMPDState') AS UnderinsuredPropertyDamageCoverageRatesUIMPDState,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'UIMPDCovered') AS UnderinsuredPropertyDamageCoverageRatesUIMPDCovered,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'UIMPDEligiblity') AS UnderinsuredPropertyDamageCoverageRatesUIMPDEligiblity,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'TotalUIMPD') AS UnderinsuredPropertyDamageCoverageRatesTotalUIMPD,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'Premium') AS UnderinsuredPropertyDamageCoverageRatesPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'WrittenPremium') AS UnderinsuredPropertyDamageCoverageRatesWrittenPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'ChangeType') AS UnderinsuredPropertyDamageCoverageRatesChangeType,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'FullTermPremium') AS UnderinsuredPropertyDamageCoverageRatesFullTermPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'ProratedPremium') AS UnderinsuredPropertyDamageCoverageRatesProratedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'ProratedPriorPremium') AS UnderinsuredPropertyDamageCoverageRatesProratedPriorPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'ChangeProrateFactor') AS UnderinsuredPropertyDamageCoverageRatesChangeProrateFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'ChangePremium') AS UnderinsuredPropertyDamageCoverageRatesChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'ProratedChangePremium') AS UnderinsuredPropertyDamageCoverageRatesProratedChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'WaivedOffPremium') AS UnderinsuredPropertyDamageCoverageRatesWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'TotalWaivedOffPremium') AS UnderinsuredPropertyDamageCoverageRatesTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'PremiumPriorToProrata') AS UnderinsuredPropertyDamageCoverageRatesPremiumPriorToProrata,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'UIMPDCoveragePremium') AS UnderinsuredPropertyDamageCoverageRatesUIMPDCoveragePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'UIMPDCoverageRate') AS UnderinsuredPropertyDamageCoverageRatesUIMPDCoverageRate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'BaseRateUIMPD') AS UnderinsuredPropertyDamageCoverageRatesBaseRateUIMPD,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'TotalPremium') AS UnderinsuredPropertyDamageCoverageRatesTotalPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'Radius1') AS UninsuredBodilyInjuryCoverageRatesRadius1,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'Radius2') AS UninsuredBodilyInjuryCoverageRatesRadius2,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'Radius3') AS UninsuredBodilyInjuryCoverageRatesRadius3,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'Radius4') AS UninsuredBodilyInjuryCoverageRatesRadius4,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'RadiusFactor1') AS UninsuredBodilyInjuryCoverageRatesRadiusFactor1,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'RadiusFactor2') AS UninsuredBodilyInjuryCoverageRatesRadiusFactor2,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'RadiusFactor3') AS UninsuredBodilyInjuryCoverageRatesRadiusFactor3,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'RadiusFactor4') AS UninsuredBodilyInjuryCoverageRatesRadiusFactor4,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'RadiusFactor') AS UninsuredBodilyInjuryCoverageRatesRadiusFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'UMBICoverageFactor') AS UninsuredBodilyInjuryCoverageRatesUMBICoverageFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'UMBIState') AS UninsuredBodilyInjuryCoverageRatesUMBIState,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'UMBICovered') AS UninsuredBodilyInjuryCoverageRatesUMBICovered,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'UMBIEligiblity') AS UninsuredBodilyInjuryCoverageRatesUMBIEligiblity,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'TotalUMBI') AS UninsuredBodilyInjuryCoverageRatesTotalUMBI,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'Premium') AS UninsuredBodilyInjuryCoverageRatesPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'WrittenPremium') AS UninsuredBodilyInjuryCoverageRatesWrittenPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'ChangeType') AS UninsuredBodilyInjuryCoverageRatesChangeType,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'FullTermPremium') AS UninsuredBodilyInjuryCoverageRatesFullTermPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'ProratedPremium') AS UninsuredBodilyInjuryCoverageRatesProratedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'ProratedPriorPremium') AS UninsuredBodilyInjuryCoverageRatesProratedPriorPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'ChangeProrateFactor') AS UninsuredBodilyInjuryCoverageRatesChangeProrateFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'ChangePremium') AS UninsuredBodilyInjuryCoverageRatesChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'ProratedChangePremium') AS UninsuredBodilyInjuryCoverageRatesProratedChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'WaivedOffPremium') AS UninsuredBodilyInjuryCoverageRatesWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'TotalWaivedOffPremium') AS UninsuredBodilyInjuryCoverageRatesTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'PremiumPriorToProrata') AS UninsuredBodilyInjuryCoverageRatesPremiumPriorToProrata,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'BaseRateUMBI') AS UninsuredBodilyInjuryCoverageRatesBaseRateUMBI,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'BodyTypeBusinessClassVehicleFactor') AS UninsuredBodilyInjuryCoverageRatesBodyTypeBusinessClassVehicleFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'BodyTypeBusinessClassFactor') AS UninsuredBodilyInjuryCoverageRatesBodyTypeBusinessClassFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'BodyTypeBusinessClassTrailerFactor') AS UninsuredBodilyInjuryCoverageRatesBodyTypeBusinessClassTrailerFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'RatedPremium') AS UninsuredBodilyInjuryCoverageRatesRatedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'UMBICoveragePremium') AS UninsuredBodilyInjuryCoverageRatesUMBICoveragePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'UMBICoverageRate') AS UninsuredBodilyInjuryCoverageRatesUMBICoverageRate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'USDOTViolationsFactor') AS UninsuredBodilyInjuryCoverageRatesUSDOTViolationsFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'USDOTBasicViolationsFactor') AS UninsuredBodilyInjuryCoverageRatesUSDOTBasicViolationsFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'BodyTypeBusinessClassFactorToUse') AS UninsuredBodilyInjuryCoverageRatesBodyTypeBusinessClassFactorToUse,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'USDOTFactor') AS UninsuredBodilyInjuryCoverageRatesUSDOTFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'TotalPremium') AS UninsuredBodilyInjuryCoverageRatesTotalPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'Radius1') AS UninsuredPropertyDamageCoverageRatesRadius1,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'Radius2') AS UninsuredPropertyDamageCoverageRatesRadius2,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'Radius3') AS UninsuredPropertyDamageCoverageRatesRadius3,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'Radius4') AS UninsuredPropertyDamageCoverageRatesRadius4,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'RadiusFactor1') AS UninsuredPropertyDamageCoverageRatesRadiusFactor1,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'RadiusFactor2') AS UninsuredPropertyDamageCoverageRatesRadiusFactor2,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'RadiusFactor3') AS UninsuredPropertyDamageCoverageRatesRadiusFactor3,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'RadiusFactor4') AS UninsuredPropertyDamageCoverageRatesRadiusFactor4,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'RadiusFactor') AS UninsuredPropertyDamageCoverageRatesRadiusFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'UMPDCoverageFactor') AS UninsuredPropertyDamageCoverageRatesUMPDCoverageFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'UMPDState') AS UninsuredPropertyDamageCoverageRatesUMPDState,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'UMPDCovered') AS UninsuredPropertyDamageCoverageRatesUMPDCovered,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'UMPDEligiblity') AS UninsuredPropertyDamageCoverageRatesUMPDEligiblity,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'TotalUMPD') AS UninsuredPropertyDamageCoverageRatesTotalUMPD,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'Premium') AS UninsuredPropertyDamageCoverageRatesPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'WrittenPremium') AS UninsuredPropertyDamageCoverageRatesWrittenPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'ChangeType') AS UninsuredPropertyDamageCoverageRatesChangeType,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'FullTermPremium') AS UninsuredPropertyDamageCoverageRatesFullTermPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'ProratedPremium') AS UninsuredPropertyDamageCoverageRatesProratedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'ProratedPriorPremium') AS UninsuredPropertyDamageCoverageRatesProratedPriorPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'ChangeProrateFactor') AS UninsuredPropertyDamageCoverageRatesChangeProrateFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'ChangePremium') AS UninsuredPropertyDamageCoverageRatesChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'ProratedChangePremium') AS UninsuredPropertyDamageCoverageRatesProratedChangePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'WaivedOffPremium') AS UninsuredPropertyDamageCoverageRatesWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'TotalWaivedOffPremium') AS UninsuredPropertyDamageCoverageRatesTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'PremiumPriorToProrata') AS UninsuredPropertyDamageCoverageRatesPremiumPriorToProrata,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'BaseRateUMPD') AS UninsuredPropertyDamageCoverageRatesBaseRateUMPD,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'BodyTypeBusinessClassVehicleFactor') AS UninsuredPropertyDamageCoverageRatesBodyTypeBusinessClassVehicleFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'BodyTypeBusinessClassFactor') AS UninsuredPropertyDamageCoverageRatesBodyTypeBusinessClassFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'BodyTypeBusinessClassTrailerFactor') AS UninsuredPropertyDamageCoverageRatesBodyTypeBusinessClassTrailerFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'RatedPremium') AS UninsuredPropertyDamageCoverageRatesRatedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'UMPDCoveragePremium') AS UninsuredPropertyDamageCoverageRatesUMPDCoveragePremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'UMPDCoverageRate') AS UninsuredPropertyDamageCoverageRatesUMPDCoverageRate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'USDOTViolationsFactor') AS UninsuredPropertyDamageCoverageRatesUSDOTViolationsFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'USDOTBasicViolationsFactor') AS UninsuredPropertyDamageCoverageRatesUSDOTBasicViolationsFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'TotalPremium') AS UninsuredPropertyDamageCoverageRatesTotalPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'USDOTViolationsFactor') AS AutoLiabilityBIPDCoverageRatesUSDOTViolationsFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'USDOTBasicViolationsFactor') AS AutoLiabilityBIPDCoverageRatesUSDOTBasicViolationsFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'USDOTFactor') AS UninsuredPropertyDamageCoverageRatesUSDOTFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'USDOTFactor') AS UnderinsuredBodilyInjuryCoverageRatesUSDOTFactor,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'RateToUseCount') AS AutoPhysicalDamageCoverageRatesRateToUseCount,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'TrailerIndicator') AS AutoLiabilityBIPDCoverageRatesTrailerIndicator,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'MidRangeFactor0To50') AS AutoLiabilityBIPDCoverageRatesMidRangeFactor0To50,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'MidRangeFactor51To200') AS AutoLiabilityBIPDCoverageRatesMidRangeFactor51To200,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'MidRangeFactor201To500') AS AutoLiabilityBIPDCoverageRatesMidRangeFactor201To500,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'MidRangeFactor501Plus') AS AutoLiabilityBIPDCoverageRatesMidRangeFactor501Plus,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'TrailerIndicator') AS HiredNonOwnedAutoCoverageRatesTrailerIndicator,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'RadiusRange') AS AutoLiabilityBIPDCoverageRatesRadiusRange,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'RadiusRange1') AS AutoLiabilityBIPDCoverageRatesRadiusRange1,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'RadiusRange2') AS AutoLiabilityBIPDCoverageRatesRadiusRange2,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'RadiusRange3') AS AutoLiabilityBIPDCoverageRatesRadiusRange3,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'RadiusRange4') AS AutoLiabilityBIPDCoverageRatesRadiusRange4,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'RadiusOne') AS AutoLiabilityBIPDCoverageRatesRadiusOne,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'RadiusTwo') AS AutoLiabilityBIPDCoverageRatesRadiusTwo,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'RadiusThree') AS AutoLiabilityBIPDCoverageRatesRadiusThree,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'RadiusFour') AS AutoLiabilityBIPDCoverageRatesRadiusFour,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TowingStorageAndLaborCoverageRates'), 'VehicleType') AS TowingStorageAndLaborCoverageRatesVehicleType,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'USDOTViolationsFactor') AS AutoLiabilityUMUIMCoverageRatesUSDOTViolationsFactor,
        JSONExtractString(vehicle_schedule, 'DeductiblePreference') AS DeductiblePreference,
        JSONExtractString(vehicle_schedule, 'MinimumPremium0to50') AS MinimumPremium0to50,
        JSONExtractString(vehicle_schedule, 'MinimumPremium51to200') AS MinimumPremium51to200,
        JSONExtractString(vehicle_schedule, 'MinimumPremium201to500') AS MinimumPremium201to500,
        JSONExtractString(vehicle_schedule, 'CalculatedMinimumPremium0to50') AS CalculatedMinimumPremium0to50,
        JSONExtractString(vehicle_schedule, 'CalculatedMinimumPremium51to200') AS CalculatedMinimumPremium51to200,
        JSONExtractString(vehicle_schedule, 'CalculatedMinimumPremium201to500') AS CalculatedMinimumPremium201to500,
        JSONExtractString(vehicle_schedule, 'CalculatedMinimumPremium501Plus') AS CalculatedMinimumPremium501Plus,
        JSONExtractString(vehicle_schedule, 'MinimumPremium501Plus') AS MinimumPremium501Plus,
        JSONExtractString(vehicle_schedule, 'ZipCode') AS ZipCode,
        JSONExtractString(vehicle_schedule, 'ALVehiclePremuim') AS ALVehiclePremuim,
        JSONExtractString(vehicle_schedule, 'APDVehiclePremuim') AS APDVehiclePremuim,
        JSONExtractString(vehicle_schedule, 'IsTrailer') AS IsTrailer,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'CoverageOnPolicyIndicator') AS AutoLiabilityBIPDCoverageRatesCoverageOnPolicyIndicator,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'MaxPremium') AS AutoLiabilityBIPDCoverageRatesMaxPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'CoverageOnPolicyIndicator') AS UninsuredBodilyInjuryCoverageRatesCoverageOnPolicyIndicator,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'CoverageOnPolicyIndicator') AS UninsuredPropertyDamageCoverageRatesCoverageOnPolicyIndicator,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'CoverageOnPolicyIndicator') AS UnderinsuredBodilyInjuryCoverageRatesCoverageOnPolicyIndicator,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'CoverageOnPolicyIndicator') AS MedicalPaymentsCoverageRatesCoverageOnPolicyIndicator,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'CoverageOnPolicyIndicator') AS PersonalInjuryProtectionCoverageRatesCoverageOnPolicyIndicator,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'CoverageOnPolicyIndicator') AS AutoLiabilityUMUIMCoverageRatesCoverageOnPolicyIndicator,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'CoverageOnPolicyIndicator') AS UnderinsuredPropertyDamageCoverageRatesCoverageOnPolicyIndicator,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'CoverageOnPolicyIndicator') AS HiredNonOwnedAutoCoverageRatesCoverageOnPolicyIndicator,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'CoverageOnPolicyIndicator') AS AutoPhysicalDamageCoverageRatesCoverageOnPolicyIndicator,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'TowingStorageAndLaborCoverageRates'), 'CoverageOnPolicyIndicator') AS TowingStorageAndLaborCoverageRatesCoverageOnPolicyIndicator,
        JSONExtractString(vehicle_schedule, 'CoverageStartDate') AS VehicleScheduleCoverageStartDate,
        JSONExtractString(vehicle_schedule, 'ChangeEffectiveDate') AS VehicleScheduleChangeEffectiveDate,
        JSONExtractString(vehicle_schedule, 'CoverageStopDate') AS VehicleScheduleCoverageStopDate,
        JSONExtractString(vehicle_schedule, 'WrittenPremium') AS VehicleScheduleWrittenPremium,
        JSONExtractString(vehicle_schedule, 'PriorChargedPremium') AS VehicleSchedulePriorChargedPremium,
        JSONExtractString(vehicle_schedule, 'ChangeType') AS VehicleScheduleChangeType,
        JSONExtractString(vehicle_schedule, 'WaivedOffPremium') AS VehicleScheduleWaivedOffPremium,
        JSONExtractString(vehicle_schedule, 'TotalWaivedOffPremium') AS VehicleScheduleTotalWaivedOffPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'PriorChargedPremium') AS AutoLiabilityBIPDCoverageRatesPriorChargedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'CoverageStartDate') AS AutoLiabilityBIPDCoverageRatesCoverageStartDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'ChangeEffectiveDate') AS AutoLiabilityBIPDCoverageRatesChangeEffectiveDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'CoverageStopDate') AS AutoLiabilityBIPDCoverageRatesCoverageStopDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'PriorChargedPremium') AS UninsuredBodilyInjuryCoverageRatesPriorChargedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'CoverageStartDate') AS UninsuredBodilyInjuryCoverageRatesCoverageStartDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'ChangeEffectiveDate') AS UninsuredBodilyInjuryCoverageRatesChangeEffectiveDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredBodilyInjuryCoverageRates'), 'CoverageStopDate') AS UninsuredBodilyInjuryCoverageRatesCoverageStopDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'PriorChargedPremium') AS UninsuredPropertyDamageCoverageRatesPriorChargedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'CoverageStartDate') AS UninsuredPropertyDamageCoverageRatesCoverageStartDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'ChangeEffectiveDate') AS UninsuredPropertyDamageCoverageRatesChangeEffectiveDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UninsuredPropertyDamageCoverageRates'), 'CoverageStopDate') AS UninsuredPropertyDamageCoverageRatesCoverageStopDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'PriorChargedPremium') AS UnderinsuredBodilyInjuryCoverageRatesPriorChargedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'CoverageStartDate') AS UnderinsuredBodilyInjuryCoverageRatesCoverageStartDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'ChangeEffectiveDate') AS UnderinsuredBodilyInjuryCoverageRatesChangeEffectiveDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredBodilyInjuryCoverageRates'), 'CoverageStopDate') AS UnderinsuredBodilyInjuryCoverageRatesCoverageStopDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'PriorChargedPremium') AS MedicalPaymentsCoverageRatesPriorChargedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'CoverageStartDate') AS MedicalPaymentsCoverageRatesCoverageStartDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'ChangeEffectiveDate') AS MedicalPaymentsCoverageRatesChangeEffectiveDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'MedicalPaymentsCoverageRates'), 'CoverageStopDate') AS MedicalPaymentsCoverageRatesCoverageStopDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'PriorChargedPremium') AS PersonalInjuryProtectionCoverageRatesPriorChargedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'CoverageStartDate') AS PersonalInjuryProtectionCoverageRatesCoverageStartDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'ChangeEffectiveDate') AS PersonalInjuryProtectionCoverageRatesChangeEffectiveDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'PersonalInjuryProtectionCoverageRates'), 'CoverageStopDate') AS PersonalInjuryProtectionCoverageRatesCoverageStopDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'PriorChargedPremium') AS AutoLiabilityUMUIMCoverageRatesPriorChargedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'CoverageStartDate') AS AutoLiabilityUMUIMCoverageRatesCoverageStartDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'ChangeEffectiveDate') AS AutoLiabilityUMUIMCoverageRatesChangeEffectiveDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityUMUIMCoverageRates'), 'CoverageStopDate') AS AutoLiabilityUMUIMCoverageRatesCoverageStopDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'PriorChargedPremium') AS UnderinsuredPropertyDamageCoverageRatesPriorChargedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'CoverageStartDate') AS UnderinsuredPropertyDamageCoverageRatesCoverageStartDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'ChangeEffectiveDate') AS UnderinsuredPropertyDamageCoverageRatesChangeEffectiveDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'UnderinsuredPropertyDamageCoverageRates'), 'CoverageStopDate') AS UnderinsuredPropertyDamageCoverageRatesCoverageStopDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'PriorChargedPremium') AS HiredNonOwnedAutoCoverageRatesPriorChargedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'CoverageStartDate') AS HiredNonOwnedAutoCoverageRatesCoverageStartDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'ChangeEffectiveDate') AS HiredNonOwnedAutoCoverageRatesChangeEffectiveDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'HiredNonOwnedAutoCoverageRates'), 'CoverageStopDate') AS HiredNonOwnedAutoCoverageRatesCoverageStopDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'PriorChargedPremium') AS AutoPhysicalDamageCoverageRatesPriorChargedPremium,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'CoverageStartDate') AS AutoPhysicalDamageCoverageRatesCoverageStartDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'ChangeEffectiveDate') AS AutoPhysicalDamageCoverageRatesChangeEffectiveDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoPhysicalDamageCoverageRates'), 'CoverageStopDate') AS AutoPhysicalDamageCoverageRatesCoverageStopDate,
        JSONExtractString(JSONExtractString(vehicle_schedule, 'AutoLiabilityBIPDCoverageRates'), 'MinimumPremiumApplies') AS AutoLiabilityBIPDCoverageRatesMinimumPremiumApplies
    FROM solartis_wip_submissions.raw_submissions
    ARRAY JOIN JSONExtractArrayRaw(JSONExtractRaw(json, 'Account'), 'Insured') AS insured
    ARRAY JOIN JSONExtractArrayRaw(JSONExtractRaw(insured, 'CommercialAutomobile'), 'Location') AS location
    ARRAY JOIN JSONExtractArrayRaw(location, 'VehicleSchedule') AS vehicle_schedule
);

